### ISSUE TITLE
[Question] Why use fence instead of memory order on load/store?

### ISSUE THREAD

**Issue by codingskynet** [kaist-cp/cs431#344]
On seqlock.rs, it uses `fence` for synchronization on `write_lock` and `read_validate`. I think that it can be also correct when using `self.seq.compare_exchange(..., Ordering::Release)` on `write_lock` and `self.seq.load(Ordering::Acquire)` on `read_validate` instead using `fence`. Why does `SeqLock` use `fence`? Also, what is difference between fence and load/store with memory ordering in detail?

**Comment by drzix** [comment]
Thanks for your good question!

## Correctness requirements of seq lock

Sequence lock has a requirement: if `R(2n)` observes `W(2n)`'s writes, then `R(2n)` validation must fail.
(where `W(2n)` (resp. `R(2n)`) is critical section that holds the write lock (resp. read) with sequence `2n`)

## `cas(Rel)`-`load(Acq)` synchronization cannot guarantee seq lock requirement

By Promising semantics, it is easy to find out that the synchronization is incorrect:

```rust
// Initially, DATA=SEQ=0

// Writer side
let s = SEQ // "0@0"
SEQ.cas(s, s + 1, Rel) // Get write lock (SEQ: "0@0"->"1@1")
DATA = 666 // Change DATA (DATA: "0@0"->"666@2")
...
||
// Reader side
let s = SEQ // Get read lock (SEQ: "0@0")
...
a = DATA // "666@2" can be read from DATA.
s ==? SEQ.load(Acq) // Validate read lock: this thread still can read "SEQ=0@0", which makes this lock incorrect.
```

## solution 1

To make it correct, the reader's view should be large enough to guarantee seeing the newest write in `SEQ`.
To make this work, the writer must use `Rel` for all its write and the reader must use `Acq` for all its read
so that the reader can see the new message in `SEQ`.
However, this is not ideal for performance and it imposes additional requirements to the client of seq lock.

## solution 2: Amortizing the synchronization cost with `fence(Rel)`-`fence(Acq)`

We can use fence for the above purpose:
- A release-fence makes messages after the fence have the same message view as thread view before the fence.
  In this example, `fence(Rel)` makes `DATA = 666` have a message view containing "SEQ: 1@1"
- An acquire-fence joins thread view with message views that the thread has brought so far before the fence.
  In this example, `fence(Acq)` makes thread view contain "SEQ: 1@1"

Promising semantics describes seq lock synchronization in the following way:

```rust
// Initially, DATA=SEQ=0

// Writer side
let s = SEQ // "0@0"
SEQ.cas(s, s + 1, _) // Get write lock ("0@0"->"1@1")
fence(Rel) // Every message written after this fence has a message view containing "SEQ: 1@1"
DATA = 666 // Change DATA ("0@0"->"666@2").
...
||
// Reader side
let s = SEQ // Get read lock ("0@0")
...
a = DATA // This thread can read "DATA=666@2", taking the view on DATA containing "SEQ: 1@1".
fence(Acq) // The fact that SEQ is at least @1 is acknowledged now. (Increasing thread view)
s ==? SEQ // "0@0" cannot be read from SEQ anymore.
```

In fact, Rel-Acq synchronization among fences is not thoroughly covered in the class.
If you want to know more details, please read the original [paper](https://sf.snu.ac.kr/publications/promising.pdf) of Promising semantics (Section 4.6 & Figure 3).

**Comment by codingskynet** [comment]
I did a mistake that `SEQ` should be read as "1@1" if `DATA` was read as "666@2" w/o fences. Thank you for explaining in detail!

**Comment by codingskynet** [comment]
I have another question but I think this question is far from the lecture. 
I had understood the mechanism using Promising semantics informally. But, I also wonder how to explain the mechanism by the definition of fence. From [documentation](https://doc.rust-lang.org/std/sync/atomic/fn.fence.html),

> A fence ‘A’ which has (at least) Release ordering semantics, synchronizes with a fence ‘B’ with (at least) Acquire semantics, if and only if there exist operations X and Y, both operating on some atomic object ‘M’ such that A is sequenced before X, Y is synchronized before B and Y observes the change to M. This provides a happens-before dependence between A and B.

Also, since Rust has the same memory model to C++20, from [C++20 standard](http://open-std.org/jtc1/sc22/wg21/docs/papers/2020/n4868.pdf),

> 31.11 Fences
2 A release fence A synchronizes with an acquire fence B if there exist atomic operations X and Y , both
operating on some atomic object M, such that A is sequenced before X, X modifies M, Y is sequenced
before B, and Y reads the value written by X or a value written by any side effect in the hypothetical release
sequence X would head if it were a release operation.

Both say that for the synchronization of fence, there should be like:

Some writes
Release fence
Atomic write
......
Atomic read
Acquire fence
Some reads

But, on seqlock it is implemented like:
```rust
// Writer side
let s = SEQ
SEQ.cas(s, s + 1, _) // some writes
fence(Rel) // release fence
DATA = 666 // non-atomic write
...
||
// Reader side
let s = SEQ
...
a = DATA // non-atomic read
fence(Acq) // acquire fence
s ==? SEQ // some reads
```

Instead of atomics, seqlock uses non-atomic objects. How to explain the mechanism from those descriptions? Also, can the standalone fences synchronize with each other?

**Comment by drzix** [comment]
- Operations on `DATA` should be atomic read/writes. In the code(`seqlock.rs`), `WriteGuard` doesn't implement `DerefMut` so that we cannot non-atomically write on the protected `data`.
- No, non-atomic accesses can never achieve synchronization, even together with fences. (Please see the section 4.3 in the [paper](https://sf.snu.ac.kr/publications/promising.pdf))

**Comment by codingskynet** [comment]
Oh, `WriteGuard` makes `DATA` modified only by atomic writing, only providing `Deref`. I was confused because the type of `SeqLock` data can be non-atomic type. Thank you very much!!!
