### ISSUE TITLE
[Question] About promising semantics..

### ISSUE THREAD

**Issue by anonymous1782** [kaist-cp/cs431#524]
Promising semantics를 하는 과정에서 조금 기초적인 질문이 있어 문의드립니다.

![image](https://user-images.githubusercontent.com/92641652/137750554-07568c20-9173-457f-92b1-5d3be334bf1d.png)

1. 해당 과정에서 Thread 1은 X의 값으로 0이 아닌 1을 선택합니다.
그 이유가 무엇인가요?

(1) Certificate의 re-certificate를 위하여
(2) 상관은 없으나 r1=r2=1이 allowed 되는지 확인을 위하여
(3) Promising modeling 과정에서 0을 선택하는 것은 strictly prohibited 이므로

2. Promises가 가능한 thread가 여러 개라면 하나만 promises 하고 re-certificate를 해도 되는 건가요?
e.g.) x=1 || y=1 || z=1

3. 대략적으로 감만 잡고 있지만, 정확한 이해를 위해 promising semantics modeling을 하는 이유와 과정이 궁금합니다. 
Promises를 한 뒤에 re-certificate 됨을 보임으로써, register의 (dis)allow 여부를 알기 위한 것이 궁극적인 목적인가요?
아니면 register의 (dis)allow 여부는 오로지 부수적인 요소이고 promising semantics modeling과 무관한 요소인가요?

**Comment by anonymous1782** [comment]
+) https://github.com/kaist-cp/cs431/issues/136 해당 글을 읽고 있습니다.

`Causality test case 17
Initially,  x = y = 0

Thread 1:
1) r3 = x
2) if (r3 != 42)
3)   x = 42
4) r1 = x
5) y = r1

Thread 2:
r2 = y
x = r2

Behavior in question: r1 == r2 == r3 == 42

Decision: Allowed. A compiler could determine that at r1 = x in thread 1,
  is must be legal for to read x and see the value 42. Changing r1 = x 
  to r1 = 42 would allow y = r1 to be transformed to y = 42 and performed
  earlier, resulting in the behavior in question.`



제가 훑은 바에 따르면, test 17같은 경우는 compiler optimization에 의해 thread 1의 4)가 r1=42로 저절로 치환이 되고, 마지막에는 결국 Y=42가 promise 된다고 이해했습니다. 제가 이해한 바가 맞을까요?

**Comment by tomtomjhj** [comment]
The purpose of the language semantics is to describe how the language behaves. In a sense, it's the specification/reference/documentation/... of the language. The semantics provides users of the language with a set of guarantees about how the program written in that language behaves. The users uses these guarantees to write correct programs. On the other hand, implementers of the language (compiler, interpreter, hardware, …) implement the language in a way that does not violate the guarantees of the semantics.

For the ease of developing in the language, it's better to have a strict semantics that only allows a small set of behaviors. We as a user want to know if `r1 = r2 = 1` is possible in the program, perhaps because we don't want that to happen for the correctness of the program and decide whether we should add more synchronization. On the other hand, in the perspective complier/hardware/... design, semantics that allows more behaviors may be desirable because it allows more optimization. Compiler/hardware/.. designers want to know if `r1 = r2 = 1` is possible, because if it's possible, they can add more optimizations (e.g. "A compiler could determine that ...").

But the problem with the memory model/semantics is that

> Despite many years of research, it has proven very difficult to develop a memory model for concurrent programming languages that adequately balances the conflicting desiderata of programmers, compilers, and hardware.
(excerpt from the promising semantics paper)

Promising semantics is an attempt to find such a semantics:

> In this paper, we propose the first relaxed memory model that (1) accounts for a broad spectrum of features from the C++11 concurrency model, (2) is implementable, in the sense that it provably validates many standard compiler optimizations and reorderings, as well as standard compilation schemes to x86-TSO and Power, (3) justifies simple invariant-based reasoning, thus demonstrating the absence of bad "out-of-thin-air" behaviors, [...]
(excerpt from the promising semantics paper)

I hope this answers 3.

* 1: (2)
* 2: yes

**Comment by anonymous1782** [comment]
Thank you for your answer. Could you answer the two additional questions?

1) https://github.com/kaist-cp/cs431/issues/524#issuecomment-945870000
2) I'm not sure what the slides want to say.
![image](https://user-images.githubusercontent.com/92641652/137839565-6cadb0bd-34c3-40b4-86d1-1a1806ea0767.png)

As far as I know, the thread view is just to represent the coherence. and the view model can cover all kinds of coherences. right?

**Comment by tomtomjhj** [comment]
1. A better explanation would be like this.
   Compiler designer wants the compiler to optimize the thread 1's `y = r1` to `y = 42` because it doesn't change the behavior of thread 1. However, if such an optimization is allowed, thread 2 may observe `r2 == 42`, which is quite weird. To make sense of this situation, users of the language should learn what optimizations the compiler/hardware may perform.
   This is not desirable because compilers/hardwares are complex. A better approach is to make a semantics of the language that abstracts such behaviors. Users only need to learn the abstract model of the language without the need to worry about the actual implementation/optimization under the hood, because the implementers of the language will make sure that the program written in the language will present the behaviors that are allowed by the semantics.
   Thus, you can understand test cases in 2 perspectives.
   Compiler designers want to optimize `y = r1` to `y = 42`. Is this optimization ok (despite that it result in `r2 == 42`)? According to Promising semantics, thread 1 can promise `y = 42`, etc ... , resulting in `r2 == 42`. Therefore, it's ok to perform this optimization since it doesn't introduce a behavior not allowed by the semantics.
   Language users want to know if `r2 == 42` is possible because it may affect the correctness of the program. They check if that is possible by following the rules of Promising semantics (thread 1 can promise `y = 42`, etc ...). Importantly, they don't need to think about the details of the compiler optimization that transforms `y = r1` to `y = 42`.
   Anyway, `r1 == r2 == r3 == 42` is possible, because thread 1 can promise `y = 42`. See https://github.com/kaist-cp/cs431/issues/136#issuecomment-708112895 the complete steps.

2. Right.

**Comment by anonymous1782** [comment]
Thank you for detailed answer! I can understand promising semantics more!

Sorry, but I have one more additional questions about acquire/release.

Y.store(1, release) and Y.load(acquire) means, only the instruction related Y can not be reordered throughout Y.store(1, release)  or Y.load(acquire)? or Other independent instruction also can not be reordered?
