### ISSUE TITLE
[Question] HW3 memory problem for try_unwrap and ordering problem for clone_drop_atomic

### ISSUE THREAD

**Issue by kaist-kihwan** [kaist-cp/cs431#532]
I can see many closed issues talking about memory problem of try_unwrap. I already read them multiple times and still don't know how to solve this. If I just implement it, address sanitizer raise memory-leak and if I try to deallocate by using `Box::from_raw` address sanitizer raise use-after-free.

Also, my implementation fails for correctness check of clone_drop_atomic. I already read lecture slides and rust documents etc. multiple times but still confused. I used `Ordering::Acquire` to instruction which loading part is important and `Ordering::Release` to instruction which storing part is important. Am I doing right?

**Comment by drzix** [comment]
While preparing midterm exam, we've studied many times what actually `Ordering::Acquire` and `Ordering::Release` do ! :) Please carefully reason about your code with Promising semantics.

If you think your code fails for the correctness check because of "ordering", I recommend you try to check if it works well when you replace all orderings with `Ordering::Seqcst`.

**Comment by kaist-kihwan** [comment]
Thank you! Changing all occurrence of Ordering to `Ordering::SeqCst` helps a lot to check what's the problem.
