### ISSUE TITLE
[Question] `protect` in Hazard Pointers (HP)

### ISSUE THREAD

**Issue by yj-han** [kaist-cp/cs431#555]
I have a few questions on the video lecture about [hazard pointers](https://www.youtube.com/watch?v=drXrIVfBKaQ&list=PL5aMzERQ_OZ9j40DJNlsem2qAGoFbfwb4&index=27).

1. Around 30:00, there are lines of code for `pop` operation:
```rust
loop {
    ...
    protect(cur);
    if (this->head.load() != cur)
      continue;
    
    // dereference to cur after protecting it
    next = cur->next;
    ...
}
```
Does `protect(cur)` detect the use-after-free when `cur` is freed before being protected? (Related to an example for chained retirement as well)

2. Also, if many threads are attempting to use global hazard pointers, it seems like the internal implementations of hazard pointers should also be a concurrent data structure (CDS). The lecture said hazard pointers use expensive fences.
   Do hazard pointers use concurrent linked list algorithms that we learned with strong fences or have unique linked list algorithms? I'm also curious about if hazard pointers themselves require safe memory reclamation.

**Comment by tomtomjhj** [comment]
1. `protect` itself doesn't detect use-after-free. It just requests that `cur` should not be freed.  `this->head.load() != cur` is what does the actual detection. Note that `cur` could already have been freed right before `protect(cur)`.  Since there is an agreement (API requirement) that `cur` can be freed only after being unlinked from the data structure, if `cur` is freed, then `this->head.load()` will load something other than `cur`. So, "`cur` is freed" implies `this->head.load() != cur`. In other words, `this->head.load() == cur` implies "`cur` is not freed". I have explained this point in more detail in the homework 6 documentation.
2. In fact, Crossbeam (epoch-based reclamation) itself uses Michael-Scott queue and Harris-Michael list under the hood, which uses crossbeam themselves. The version of hazard pointer you will implement in HW6 uses a lock-free data structure, but it doesn't use an SMR and instead employs its own recycling mechanism.

**Comment by yj-han** [comment]
@tomtomjhj oh, I think I have to read HW6 documents more thoroughly..! Thank you for the reply! :)
