### ISSUE TITLE
[Question] Why we need synchronization as safety objective of concurrrent data structure?

### ISSUE THREAD

**Issue by syoh0708** [kaist-cp/cs431#561]
In 74th slide of lecture slide, there is a synchronization requirement as safety of concurrent data structure.

https://youtu.be/nOEJk3vHiTs?list=PL5aMzERQ_OZ9j40DJNlsem2qAGoFbfwb4&t=116
And in above video lecture, professor says "the reason is that the queue can be used as a communication channel ~".
I think it is not general case and wonder why it should be general specification for CDS.
Is there any general needs to follow synchronization requirement?

**Comment by jeehoonkang** [comment]
We can think of data structures without synchronization guarantees, but it will be error-prone. For instance, let's think of the following program:

```
data = 42;
queue.push(1);
||
queue.pop(); // blocked when empty
printf("%d\n", data);
```

Then from the programmer's perspective, it should print 42 because the queue "transfers" the value. However, without synchronization, it is not guaranteed.

**Comment by syoh0708** [comment]
I will ask you in words in class because I don't think my intention was accurately conveyed with my short English. 😅
