### ISSUE TITLE
[Question] Meaning of "reduce cache invalidations by avoiding writes" in key idea of scalability of CDS.

### ISSUE THREAD

**Issue by syoh0708** [kaist-cp/cs431#562]
In 76th slide of lecture slide, I have a question with meaning of "reduce cache invalidations by avoiding writes" in key idea of scalability of CDS.

When I searched [optimistic concurrency control](https://en.wikipedia.org/wiki/Optimistic_concurrency_control) in wikipedia,
it says "While running, transactions use data resources without acquiring locks on those resources. Before committing, each transaction verifies that no other transaction has modified the data it has read. If the check reveals conflicting modifications, the committing transaction rolls back and can be restarted.". 

So since acquiring lock needs writing to memory and cache invalidation, is it right to reduce cache invalidation **by not using the lock in read-mostly workloads**?

**Comment by jeehoonkang** [comment]
yes, for read-mostly workloads, actually avoiding reads are crucial for performance.

**Comment by syoh0708** [comment]
> yes, for read-mostly workloads, actually avoiding reads are crucial for performance.

-> actually avoiding **writes** are crucial for performance.
I'm confused. Is it a typo?

**Comment by jeehoonkang** [comment]
@syoh0708 oh sorry, it's a typo. I just fixed it.

**Comment by syoh0708** [comment]
Thank you for reply!
I'll close this issue.

**Comment by poppindouble** [comment]
@syoh0708  Hi, maybe I can help you to clarify the idea here a little bit.

> reduce cache invalidation by avoiding writes

This is just an idea of how a CDS should scale. This idea is pretty common in different kinds of system software. 

Now, let's say we want to design a storage engine, this storage engine needs to handle a lot of concurrent requests for reading data, and rarely this storage engine needs to deal one or two write request. (Memcached, Redis caching system)

So a really straightforward design is to put as much hot data as you can into the memory CDS, try to touch the disk as less as possible, because disk IO is much expensive then memory access. But what if now a write request comes in?

> optimistic concurrency control 

There are two concepts here. 

1. Transactions. 
The definition of transactions in industrial is a mass(mainly because of the definition of isolation level is blur), for simplicity, let's say a transaction is combination of several read write operations, and all these operations touch different parts of resources of the database, for example, several different key value pairs for a KV storage engine.

2. Concurrency control
With the concept of transaction above, let's say we have tons of transactions going on in our storage engine now, and here are the situations you might have:

- We are really lucky that all transactions are just reading stuff. Serve the requests from the memory, job done.
- We are not lucky that some of the transactions step on each other's toes. 

Let's say Transaction A and D want to read Key 1, Transaction B want to modify Key1 and Value 1. Transaction C want to read Key 2. No matter what, Transaction C should be succeeds,  and let's say Transaction B is lucky enough to be the first one to commit. For simplicity, by committing means the write operation literally goes to the disk already. In this case, we can choose to roll back A and D by restart the transaction and invalid Key 1 and Value 1  in CDS in memory, and this is pretty expensive, since in real world the whole memory CDS might be reconstructed.

> So since acquiring lock needs writing to memory and cache invalidation, is it right to reduce cache invalidation by not using the lock in read-mostly workloads?

Back to your question, I think it is not acquiring lock needs writing to memory and cache invalidation. It is in a read operation intensive software, write operation might cause a lot of memory invalidation. So we want to make the read operation as simple as possible, like putting everything in memory, and only lock those data has write contention. When commit a transaction, you need to see if the data you read still valid. Actually this idea also exists in the [seqlock](https://github.com/kaist-cp/cs431/blob/main/lock/src/seqlock.rs) design. see the `read_validate` function.
