### ISSUE TITLE
[Homework 5] How can we distinguish `Atomic<T>` and `Atomic<Segment>` ?

### ISSUE THREAD

**Issue by bronte000** [kaist-cp/cs431#567]
I think we need to distinguish Atomic T and Atomic Segment to implement drop properly.
(Because we should drop segments, but not the individual elements)
But I have no idea....
Since Segment uses Atomicusize instead of Atomic, it is impossible to use tag for individual segment.

Or, should we use row pointer or Box?
But I think we still need to know the exact type to do type conversion.
I tried to use Owned::from_usize but this function required to specify the type.

**Comment by GrasshopperBears** [comment]
Maybe you can refer this issue https://github.com/kaist-cp/cs431/issues/225

**Comment by byeongkeonLee** [comment]
I'm not sure I understood your questions correctly and my opinion will be helpful, but:

The height 0 means it is a leaf node (Atomic<T>). otherwise, it is a segment node (Atomic<Segment>). 

It depends on the implementation, but you can know each segment's height by starting from the root recursively or iteratively. (BFS, DFS(recursive call), or etc..)

**Comment by bronte000** [comment]
> I'm not sure I understood your questions correctly and my opinion will be helpful, but:
> 
> The height 0 means it is a leaf node (Atomic T). otherwise, it is a segment node (Atomic Segment).
> 
> It depends on the implementation, but you can know each segment's height by starting from the root recursively or iteratively. (BFS, DFS(recursive call), or etc..)

Thank you. I think it will work!
