### ISSUE TITLE
[Question] Questions about lecture material

### ISSUE THREAD

**Issue by anonymous1782** [kaist-cp/cs431#585]
I have several questions regarding the lecture notes while I review the semester.

1. I'm currently not fully understanding the difference between MaybeUninit vs ManuallyDrop.
 I need more the reason why stack nodes use dropmanually for data while queue nodes use maybeuninit.

 (lock free 스택에서는 데이터를 위해 drop manually를 사용한 반면 큐에서는 maybeuninit을 사용합니다. 둘의 정확한 차이를 알 수 있을까요?
 a) stack의 데이터도 uninit일 수 있으나, rust의 다양한 API를 설명하기 위해 dropmanually를 사용
 b) stack과 queue에 무언가 차이가 있음

2. I;m currently not fully understanding the difference between owned vs just pointer based operation
 (Owned를 사용하면 해당 thread가 그 주소를 소유하고 있음을 보장하고, 자유롭게 접근 할 수 있다고 들었습니다. synchronization을 잘 맞춰준다면 단순히 pointer based operation을 사용하는 것도 문제가 없을 것 같은데 owned 를 사용하는 이유가 무엇인가요?)

3. In the lecture, a student asked about the CAS success and failure. Unfortunately, i'm sorry that I think the professor's answer is not clear for me. 
 The success and failure is decided at runtime, while the ordering is decided during at compile time. How does the compiler know it is possible to success or failure and order the instruction _without any runtime operation_?

It might be fundamental questions.. but I would like to make clear understanding about the ambiguous things. Thanks in advance!

**Comment by tomtomjhj** [comment]
1. In general, `ManuallyDrop<T>` and `MaybeUninit<T>`can be considered as unsafe variants of `Option<T>` for specific purposes. While unsafe, they are don't require additional runtime check and space like `Option<T>`.
    * `ManuallyDrop<T>` is for the case where the ownership of `T` can be extracted (like `Option::take`). `drop` of `ManuallyDrop<T>` does not drop `T`, because `T` might have been already extracted. Stack uses it because `pop` takes the ownership of `T` so the deferred destruction of the `Node<T>` should not drop `T`.
    * `MaybeUninit<T>` subsumes `ManuallyDrop<T>` and it can be used for cases where it may not hold a valid value of `T`. Queue uses it because the sentinel node does not hold a valid value of `T`. Similarly, `SplitOrderedList` can use `MaybeUninit<T>` for the sentinel nodes instead of `Option<T>`.

2. What's pointer-based operation? And what use case of `Owned` are you referring to?

3. Example: If the success order of CAS includes `Release`, then the compiler can insert a suitable hardware fence instruction before the CAS instruction. (Note that adding extra fences is always safe, because it does not introduce new behaviors.) If the success/failure ordering includes `Acquire` ordering, then the compiler can insert a suitable fence instruction after CAS instruction in the respective branches.

**Comment by anonymous1782** [comment]
1. I got it! Thanks.

2. Owned를 사용하는 general case에 대해서 그 이유를 완벽히 이해하지 못했습니다. std::ptr과 owned의 차이를 혼동하고 있어서 질문드렸습니다...

3. 설명해주신 내용에 따라, branch를 만들어서 해결하는 것으로 이해했습니다. 감사합니다! 

자세한 답변 감사드립니다!

**Comment by tomtomjhj** [comment]
2. In general, we prefer types like `Owned` because they encode useful information to the type, unlike raw pointers. This is good because humans are not really good at "synchronization을 잘 맞춰". Instead, we let the compiler check that, when possible.

**Comment by anonymous1782** [comment]
Thanks!!
