### ISSUE TITLE
[Question] HP-protected Treiber's stack

### ISSUE THREAD

**Issue by anonymous1782** [kaist-cp/cs431#588]
Thank you always, TA.

I think it is minor things (maybe my wrong understanding?  or maybe ppt error?),

![image](https://user-images.githubusercontent.com/92641652/146034342-d0790b9b-715f-4456-b5cd-a66a61733833.png)

Don't we need to unprotect the cur between if(this->head.load !=cur) and continue?

**Comment by tomtomjhj** [comment]
It's not strictly necessary because `protect` in the next iteration will overwrite the slot anyway. But if we want to wrap the validation part into a single function like HW6's `try_protect`, it should clear the protection. We will give full points in the exam even if the answer doesn't mention that `unprotect`.

**Comment by tomtomjhj** [comment]
Yeah `unprotect` is necessary there. But we will still give full points in the exam even if the answer forgets to mention that unprotect.

**Comment by tomtomjhj** [comment]
@jeehoonkang Please fix the slide

**Comment by jeehoonkang** [comment]
@tomtomjhj I fixed it, but I don't get the point... Why do we need to unprotect it?

**Comment by tomtomjhj** [comment]
If `cur == nullptr` in the next iteration, then the protection is not overwritten.

**Comment by anonymous1782** [comment]
Yes, I actually thought the next iterations. Thank you!

**Comment by n0gu** [comment]
I think the slide with EBR has similar issue, if we return from `if (curr == nullptr)` then `set_quiescent` is never called (although in practice we use RAII).

**Comment by jeehoonkang** [comment]
- I agree with @n0gu . It's quite severe in EBR because an absence of `set_quiescent` would block the reclamation of everything.
- For HP, I think not unprotecting a single block would not be a big problem. But I agree with @tomtomjhj and @anonymous1782  that it's better to unprotect it. Thanks for letting me know!
