### ISSUE TITLE
CS431:Environment setup

### ISSUE THREAD

**Issue by sowon63** [kaist-cp/cs431#627]
Hello!
I am the exchange student that came rather late to class (physically) due to some delays.

I was following the guide in github to prepare the environment for the projects. And since I'm more comfortable and used to programming on linux, I set up an **Ubuntu 22.04 VM** on my computer, and to avoid any losses I put the code in a **private github repository** of a new git account I made with the kaist email. But I didn't quite understand the **ssh** part. I did connect to the ssh server, and generated the keys etc, but what do we need the **ssh server** for? And what is the client?

Additional question: is there any **preferable settings for the VM**? since we are working on **concurrency**, should I use more than **4 CPUs** in the Virtual Machine?

**Comment by Lee-Janggun** [comment]
We use the server to provide students a common, strong environment to work with.

If you are fine with working on your local VM, then please do so, but note that concurrency sanitizer tests do take some time, and it make take even longer on VM.

Also, the grading will be done on the a similar server, so I do recommend working on the server if possible.

I think the client was just the most recent ubuntu.

For VM settings, I don't know, since we never tried VMs for the homework, but I would say you need >4 CPUs.

**Comment by sowon63** [comment]
I understand. 
I would prefer to have the same environment outline as the rest of teh class, so I think working on the server would be better.
So for the homeworks we need a server, which we connect to via ssh, and a client which will be the most recent ubuntu. 
So I can always use the VM I have installed as the client, and through it I can establish an ssh connection to the server.

But why is it that I can't use the commands "nano" and "sudo" when I'm working on the server?

**Comment by Lee-Janggun** [comment]
- Client: Sorry... I was a bit confused. You can use any env with suitable ssh ability as client, you don't have to use ubuntu.
- sudo: we did not give sudo permission because we do not think students need it. 
- nano: If you really prefer the nano editor, please ask the professor to install it on the server.

**Comment by sowon63** [comment]
okay! Thank you!
I prefer to use the server as it was initially provided, as I think it would be nice to discover and use a new editor, etc..

**Comment by Lee-Janggun** [comment]
Great! I think all questions are answered, so I will close this issue.

**Comment by tomtomjhj** [comment]
@sowon63 I strongly recommend you to try VSCode Remote. See the description in README.md.

**Comment by sowon63** [comment]
Yes I tried it the other day from the ubuntu VM to the server.

Thank you!
WAMRA Mouna.



-----Original Message-----
