### ISSUE TITLE
[Homework 3] How to return Result<T, ()> in remove

### ISSUE THREAD

**Issue by choejms** [kaist-cp/cs431#638]
Hi, in Homework 3's remove function, we have to return `Result<T, ()>` in `remove()` function.
However, `remove()` takes `key: &T` as a parameter, as shown below.

` pub fn remove(&self, key: &T) -> Result<T, ()> {
        .
        .
        .
        Ok(*key)
    }`

If I want to return Result<T>, I have to return Ok(*key), but the error message says "move occurs because `*key` has type `T`, which does not implement the `Copy` trait."
How can I return Result<T> since we are taking `key: &T` as a parameter?

Also, `insert()` takes `key: T` as a parameter while `remove()` takes `key: &T` as a parameter. Is this intended? If so, what is the purpose of this difference?

**Comment by Lee-Janggun** [comment]
Yes that is fully intended.

# Insert

First, notice the return type is `Result<(),T>`, and the comment `If the set already has the key, return the provided key in `Err`.`

Since we give `key: T` as a parameter, we are passing the full ownership of `T` to the set. If `T` was not in the set, than 
the set takes the ownership of`T`. 

On the other hand, if `T` was already in the set, as the comment says,`insert()` should return the ownership it received via the `Err` variant, which is why the return type is `Result<(),T>`, not `Result<(),&T>`.

# Remove

Here, unlike insert, the caller of `remove()` never intends to pass the ownership of `T` to the set. Hence it should suffice to pass a reference to `T`, not the full ownership.

Then, what should be the ownership of `T` to return? If you are returning the `Ok` variant, that means that you found the received `key` in the set. Hence, the set must have ownership of `key` inserted by the corresponding `insert()`. This inserted ownership for `key` is what you should return.

In terms of your code, you are trying to return the ownership that `key: &T` is referencing to, which is not the ownership held by the set.

**Comment by choejms** [comment]
Oh I see. Thank you for the detailed explanation.

One question I have is that
if we are removing a node B, we have to release the lock on B and drop B. 
But if we drop B, we cannot return B's ownership of the key because we cannot refer to B anymore.
If we try to return B's data without having dropped B, then the compiler will reject the code due to the movement of ownership.

To be precise, I do not understand the exact meaning of returning the "ownership for key." As soon as we wrap the node's data inside Ok(), I think we have a movement of ownership resulting in a compile error. 

Am I not understanding something correctly?

**Comment by Lee-Janggun** [comment]
Let's look at the structure of `Node<T>`.

```rust
struct Node<T> {
    data: T,
    next: Mutex<*mut Node<T>>,
}
```

As you mentioned, if we drop the entire `Node<T>`, we will drop the inner `T` as well.
 So only the `next` should be dropped or dually, we would need to return `data` before `Node<T>` goes out of scope.

The hint I can give is (1) try to utilize [`Box::from_raw()`](https://doc.rust-lang.org/std/boxed/struct.Box.html#method.from_raw) and (2) noting that if you have ownership of a struct `s` with two fields `f1` and `f2`, doing `s.f1` gets ownership of just `f1`.

**Comment by choejms** [comment]
I see. I think I have a glimpse of an idea. Thank you for the explanation.
