### ISSUE TITLE
[Question HW1] Implementing `wait_empty` function

### ISSUE THREAD

**Issue by DaeyongKwon98** [kaist-cp/cs431#639]
Examples from [https://doc.rust-lang.org/stable/std/sync/struct.Condvar.html](url)
```rust
let pair = Arc::new((Mutex::new(false), Condvar::new()));
let pair2 = Arc::clone(&pair);

// Inside of our lock, spawn a new thread, and then wait for it to start.
thread::spawn(move|| {
    let (lock, cvar) = &*pair2;
    let mut started = lock.lock().unwrap();
    *started = true;
    // We notify the condvar that the value has changed.
    cvar.notify_one();
});

// Wait for the thread to start up.
let (lock, cvar) = &*pair;
let mut started = lock.lock().unwrap();
while !*started {
    started = cvar.wait(started).unwrap();
}
```
Using this example, I implement `wait_empty`. My logic is like below.
1. `pair` has `Mutex` with boolean `jobcount == 0`, and `condvar`
2. Instead of `Condvar::new()`, use `empty_condvar` in `ThreadPoolInner`.
3. To wait until `job count` becomes 0, change `*started` with boolean `jobcount == 0`, so `true` can be passed to `*started` when jobcount becomes zero.

Here, tester saids type `Condvar` doesn't implement Copy trait, so move occurs when I define `pair`. So following error occurs.
error[E0507]: cannot move out of self.empty_condvar which is behind a shared reference

Thank you.

**Comment by Lee-Janggun** [comment]
You shouldn't need to define a new pair. You can consider the `ThreadPoolInner` as a wrapper for the pair. 

That is in `wait_empty()`, the `count` field of `self` is the mutex to use with the condvar field `empty_condvar` of `self`.

The error is correct because `self` is given as a reference, so you cannot define a `pair` with it as it will take ownership of `self`, which `wait_empty()` does not have.

**Comment by DaeyongKwon98** [comment]
My `wait_empty` structure:

First I get `jobcount` - `MutexGuard<usize>` using `lock`.
Then I get `condvar` with referencing `self.empty_condvar` - `&Condvar`

I spawn the thread. Inside the thread, it makes `jobcount` to zero and call `notify_one` with `condvar`.

Finally in while loop, `condvar` `wait`s until `jobcount` becomes zero.



When I execute, following error occurs.
`error[E0277]: MutexGuard<'_, usize> cannot be sent between threads safely`
It says the trait `Send` is not implemented for `MutexGuard<_,usize>`.
How can I deal with this?

Thank you.

**Comment by Lee-Janggun** [comment]
May I ask why you are spawning a thread inside `wait_empty`?

**Comment by DaeyongKwon98** [comment]
I understand example code above like below.
When while loop calls `wait`, it keeps waiting until while condition changes (In example it means `*started` become true).
When spawned thread is executed, it makes `*started = true` and notify that value changes, so while loop exits.

So I think spawned thread's role is to change condition in while loop and notify this to finish waiting.

**Comment by Lee-Janggun** [comment]
That understanding is correct, but the thing you are missing is that the above example is doing essentially two roles, a notifier and a waiter, and our `wait_empty()` is only a waiter.

Now it should be possible for `wait_empty()` to do both, but that would be very inefficient. There is a much better place among the API of `ThreadPoolInner` to notify the condvar that the `job_count` is zero.

Some comments on your spawned thread: 
* The problem is that you are trying to use the `MutexGuard` you acquired for the waiter for the notifier. That is, you are trying to use a lock that one thread acquired by another thread. 
* This is illegal, so the compiler correctly catches that. 
* You should `lock` again inside your spawned thread if you want to access the lock.
* Also, are you saying that you simply set the `job_count = 0` inside the spawned thread? This is clearly wrong, as the role of `job_count` is to count the number of unfinished jobs, which the spawned thread does not have info.

**Comment by DaeyongKwon98** [comment]
I delete spawning a thread and change my code simpler.
My code:
First `lock` `jobcount`.
Then while `jobcount != 0`, `condvar` waits.

Here I fall into infinite loops, so I wonder how to finish waiting (or getting out of while loop).

I try some possibilities, but don't work.
- Instead of `wait` function, I use `wait_while` function. I set condition to `jobcount==0`, so that when it becomes true, waiting finishes.
- Inside while loop, I add `if jobcount==0 break`.
- Just add `break` after `wait` function.

You said that `wait_empty` doesn't need to do notifying role. Does it mean that I don't need to use `notify_one` function?
I can't clarify the procedure of finishing wait function.

**Comment by Lee-Janggun** [comment]
All I can really say is repeating my last comment: the condvar should be notified when the `job_count` goes to 0. 

That is, `nofity_{one,all}` should be called when you are sure `job_count` goes to 0, and there should be some other place then `wait_empty()` that makes much more sense to check this.

As a side note: If you want some more active help, please come to the TA session tomorrow morning.

**Comment by DaeyongKwon98** [comment]
'there should be some other place then wait_empty() that makes much more sense to check this.' <- this comment helps me a lot. I pass thread_pool :)

By the way, I pass tcp.rs while I don't use `Ordering::Release`: I only use `Ordering::Acquire`. Is it ok because I pass 1 test?

**Comment by Lee-Janggun** [comment]
> 'there should be some other place then wait_empty() that makes much more sense to check this.' <- this comment helps me a lot. I pass thread_pool :)

Glad I could help!

> By the way, I pass tcp.rs while I don't use Ordering::Release: I only use Ordering::Acquire. Is it ok because I pass 1 test?

No... I really should make a test case that penalizes this... but since the deadline is near, I'll have to let it pass.
