### ISSUE TITLE
[Question] Difference of CLH and MCS locks

### ISSUE THREAD

**Issue by choejms** [kaist-cp/cs431#653]
```rust
fn lock(&self) -> Self::Token {
        let node = Box::into_raw(Box::new(CachePadded::new(Node::new())));
        let prev = self.tail.swap(node, Ordering::AcqRel);

        if prev.is_null() {
            return Token(node);
        }

        unsafe {
            (*prev).next.store(node, Ordering::Release);
        }

        let backoff = Backoff::new();
        while unsafe { (*node).locked.load(Ordering::Acquire) } {
            backoff.snooze();
        }

        Token(node)
    }
```

Hi in the above lock() function for MCSLock, I am wondering why we have `while unsafe { (*node).locked.load(Ordering::Acquire) }`. I think it should be `while unsafe { (*prev).locked.load(Ordering::Acquire) }` like it is for CLHlock.

Can you explain why it is different?

**Comment by Lee-Janggun** [comment]
I changes the title to be more descriptive.

> How swap works for atomic_ptr

To answer the question of the original title, swap simply replaces the raw pointer that the given `AtomicPtr` points to with a new raw pointer, and returns the old pointed value. You can think of it as a CAS but skipping the comparison. As a side note, this is possible because raw pointers are `Clone`.

To answer the question of the issue, this really boils down to the motivation of MCS locks.

In a locking protocol, the necessary communication between a locking and unlocking thread is the unlocking thread to set an atomic bool to true. 

To prevent contention on a single variable, CLH and MCS locks use a linked list where each thread adds a node to the linked list that stores the atomic bool.

That is, when thread A acquires a lock, and thread B attempts to lock while A still holds it, the inner linked list will have two nodes.

```
node A : { true } --> node B : { true } 
```
The question is then  _which node_ the communication from A's unlock and B's lock takes place. 

CLH locks chooses the communication place as `node A`. Hence, in order for thread B to check that A has finished, it reads the boolean flag stored in its `prev`. Hence even after A has unlocked, access to `node A` will not finish until thread B has woken up and read the value in `node A`. To prevent use-after-free, we do deallocation of `node A` in thread B. 

This is a problem because deallocation of a memory segment allocated by a different thread is inefficient due to NUMA access (I actually don't know the detailed reasoning, and is not really the focus of this course).

MCS lock solves this by making the communication happen at `node B`.  This is made evident by the following store that does not exist in CLH locks:

https://github.com/kaist-cp/cs431/blob/f743ff1bea8b87edfad3c9a7062579d6e06e90f5/src/lock/mcslock.rs#L51

Since thread B stored `node B` to the `next` of `node A`, thread A can now access `node B`'s boolean value when unlocking the lock to tell thread B that it has finished. In particular, since thread B will not access `prev` (node A) after storing it's `node` to `next`, thread A can safely deallocate `node A`, ensuring the thread that allocated the node deallocates it.

Now of course, deallocation in thread A should be careful in that use-after-free does not occur with regards to thread B's access to node A. Reasoning about why the given implementation does not cause it is left to you (of course, you can ask it you get stuck).

**Comment by choejms** [comment]
Thank you for the amazing explanation. This made many things clear. 

I think in given implementation, use-after-free is not possible because if `node A` is the last node, then `compare_and_exchange` guarantees that when `node A` is dropped, other threads cannot access `node A` because `self.tail` is already null.
If `node A` is not the last node, there is no way for the incoming threads to access `node A` in the first place. 

Thank you.

**Comment by Lee-Janggun** [comment]
> If node A is not the last node, there is no way for the incoming threads to access `node A` in the first place.

This is incorrect. In this case, thread B can still access `node A` since it is stored in `prev`.
