### ISSUE TITLE
[Question] Implementation of MCS Lock

### ISSUE THREAD

**Issue by pr0cf5** [kaist-cp/cs431#657]
I found a [good resource](https://dl.acm.org/doi/10.1145/103727.103729) on MCS Locks, written by one of the creators.

The algorithm description in the document is as follows:
![image](https://user-images.githubusercontent.com/38807869/194595426-13fa258a-0cca-4aa4-b2ad-695bc82872c7.png)

The rust version of this is
```rust
unsafe fn unlock(&self, token: Self::Token) {
      let node = token.0;
      let mut next = (*node).next.load(Ordering::Relaxed);
      if next.is_null() {
          if self
              .tail
              .compare_exchange(node, ptr::null_mut(), Ordering::Relaxed, Ordering::Relaxed)
              .is_ok()
          {
              drop(Box::from_raw(node));
              return;
          }
          loop {
              if !(*node).next.load(Ordering::Relaxed).is_null() {
                  break;
              }
          }
      }
      next = (*node).next.load(Ordering::Relaxed);
      drop(Box::from_raw(node));
      (*next).locked.store(false, Ordering::Release);
      return;
  }
```

The implementation introduced in class:
```rust
unsafe fn unlock(&self, token: Self::Token) {
      let node = token.0;

      loop {
          let next = (*node).next.load(Ordering::Acquire);
          if !next.is_null() {
              drop(Box::from_raw(node));
              (*next).locked.store(false, Ordering::Release);
              return;
          }

          if self
              .tail
              .compare_exchange(node, ptr::null_mut(), Ordering::Release, Ordering::Relaxed)
              .is_ok()
          {
              drop(Box::from_raw(node));
              return;
          }
      }
  }
```

The difference with this implementation and the implementation introduced during the lecture is whether the CAS is used inside the loop body or not. 

It is desirable to call CAS as less as possible, as it is the source of contention. I wonder if there are any pros of executing CAS within a loop nonetheless.

**Comment by Lee-Janggun** [comment]
Slight modification with proper orderings
```rust
unsafe fn unlock(&self, token: Self::Token) {
        let node = token.0;
        let mut next = (*node).next.load(Ordering::Acquire);
        if next.is_null() {
            if self
                .tail
                .compare_exchange(node, ptr::null_mut(), Ordering::Release, Ordering::Relaxed)
                .is_ok()
            {
                drop(Box::from_raw(node));
                return;
            }

            while {
                next = (*node).next.load(Ordering::Acquire);
                next.is_null()
            } {}
        }
        drop(Box::from_raw(node));
        (*next).locked.store(false, Ordering::Release);
    }
```
To answer your question, yes, CAS in loop should be avoided if possible, since not only it is a point of contention but also takes a lot of CPU cycles.

I think that this case we can take the CAS out of the loop, since once we check once that the current lock is not the tail, we won't need to check for it again as locks go out of the inner linked list in FIFO manner.

In terms of why this was not done in the first place, I don't know as I didn't implement this. @jeehoonkang do you remember why such optimization was not done?

**Comment by woojinnn** [comment]
Can I change order between (CAS in tail) and (checking next)? I mean, is the code below also valid?  
```rust
unsafe fn unlock(&self, token: Self::Token) {
    let node = token.0;
    if self
        .tail
        .compare_exchange(node, ptr::null_mut(), Ordering::Release, Ordering::Relaxed)
        .is_ok()
    {
        drop(Box::from_raw(node));
        return;
    }

    let mut next = (*node).next.load(Ordering::Acquire);
    while {
        next = (*node).next.load(Ordering::Acquire);
        next.is_null()
    } {}

    drop(Box::from_raw(node));
    (*next).locked.store(false, Ordering::Release);
}
```
I think this one is more concise.

**Comment by Lee-Janggun** [comment]
It'll still be correct, but it will might be less efficient, since you code will _for sure_ preform a CAS, while in the above it only does a CAS when `next` is null.

Of course, deciding on which one is faster for sure theoretically is not possible because it really depends on how the above lock is used in practice: are there more cases where the a `lock()`er is waiting for another thread to unlock? If not, your answer may be better.

A way to deal with this is to give [optimization flags](https://github.com/MPI-SWS/genmc/blob/9cfca6da1119ae51f23e1779702c8484fa0e7385/tests/correct/data-structures/mcs_spinlock/mcs_spinlock.h#L99-L116) for the compiler, but AFAIK Rust does not have them, at least not in std.
