### ISSUE TITLE
Why does type Token implement Clone?

### ISSUE THREAD

**Issue by choejms** [kaist-cp/cs431#661]
Hi, in api.rs, type Token implements Clone like below.

```
pub trait RawLock: Default + Send + Sync {
    /// Raw lock's token type.
    type Token: Clone;

    /// Acquires the raw lock.
    fn lock(&self) -> Self::Token;

    /// Releases the raw lock.
    ///
    /// # Safety
    ///
    /// `unlock()` should be called with the token given by the corresponding `lock()`.
    unsafe fn unlock(&self, token: Self::Token);
}
```
I looked where `clone()` is used. And it is only used in `drop()` function. 

```
impl<'s, L: RawLock, T> Drop for LockGuard<'s, L, T> {
    fn drop(&mut self) {
        // SAFETY: since `self` was created with `lock` and it's `token`, the `token` given to
        // `unlock()` is correct.
        unsafe { self.lock.lock.unlock(self.token.clone()) };
    }
}
```
But why can't we pass self.token directly? I don't think movement of ownership is an issue because after we are dropping the LockGuard, there is no reason to use the token. Also, in all of the locks we have learned, we do not access `self.token` in `unlock()` function, so why is clone necessary?

**Comment by Lee-Janggun** [comment]
You can try removing the trait bound and see what happens:
```
error[E0507]: cannot move out of `self.token` which is behind a mutable reference
   --> src/lock/api.rs:132:40
    |
132 |         unsafe { self.lock.lock.unlock(self.token) };
    |                                        ^^^^^^^^^^ move occurs because `self.token` has type `<L as api::RawLock>::Token`, which does not implement the `Copy` trait
```

Since `token` is behind a reference, the ownership of `self.token` cannot be sent to `unlock`, which is why this occurs.

Then is there a way to delete the trait bound? The simple way is to change the API of `RawLock::unlock()` as follows to only require a token for the reference.

```rust
unsafe fn unlock(&self, token: &Self::Token);
```

However, like this, `RawLock::unlock()` no longer "take"s ownership of `Self::Token`, so the client can still access `Self::Token` which may be problematic for some tokens (although the locks we have seen does not have this problem). Also, it is a breaking change in the API for RawLock.

An alternative solution is to use [`ManuallyDrop<T>`](https://doc.rust-lang.org/stable/std/mem/struct.ManuallyDrop.html), which allows one to manually control dropping of elements, including the ability to take ownership from a mutable reference. 

After [the fix](https://github.com/kaist-cp/cs431/commit/54af04043520783d3656c7055454ef5051dff293) we have the following changes to `LockGuard` and `drop()`.
```rust
pub struct LockGuard<'s, L: RawLock, T> {
    lock: &'s Lock<L, T>,
    token: ManuallyDrop<L::Token>,
    _marker: PhantomData<*const ()>, // !Send + !Sync
}


fn drop(&mut self) {
    // SAFETY: `self.token` is not used anymore in this function, and as we are `drop`ing
    // `self`, it is not used anymore.
    let token = unsafe { ManuallyDrop::take(&mut self.token) };

    // SAFETY: since `self` was created with `lock` and it's `token`, the `token` given to
    // `unlock()` is correct.
    unsafe { self.lock.lock.unlock(token) };
}
```

Side note: you can argue that this is a problem with the `Drop` trait which does not require `self` but `&mut self`, but that's another story.

**Comment by choejms** [comment]
Thank you for the explanation!

**Comment by dubuduru** [comment]
Then is it possible to use Option<T> instead of ManuallyDrop<T>, as Option<T> also have take ownership from a mutable reference? Or ability to manually control dropping is necessary for the implementation?

**Comment by Lee-Janggun** [comment]
Yes you could do that, but note that doing so will cause an additional write to self.token, while using ManuallyDrop is 0 cost.

If you want to avoid unsafe as much as possible, Option is an better choice.
