### ISSUE TITLE
[Question HW3] Panick with initial code

### ISSUE THREAD

**Issue by DaeyongKwon98** [kaist-cp/cs431#663]
When I try `cargo test --test list_set` with initial `list_set` in `src` and `tests`, result is
```running 6 tests
thread panicked while panicking. aborting.
error: test failed, to rerun pass '--test list_set'
```

Is it normal result?
I think it should show me fail messages like this..

```
running 6 tests

test result: FAILED. 0 passed; 6 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

**Comment by Lee-Janggun** [comment]
Yes, this is expected. If you run `cargo test --test list_set -- --nocapture`, it will say that it it panicked while testing `smoke()` in `insert()` and `drop()`. One of the stuff done on panics is dropping the current resources held, which is why `drop()` is called. However, since `drop()` is `todo!()`, it will panic and cause a recursive panic leading to abort.
