### ISSUE TITLE
[Question] What is purpose of Phantomdata in LockGuard? (api.rs)

### ISSUE THREAD

**Issue by dubuduru** [kaist-cp/cs431#667]
As far I understood, phantomdata<T> is for mimicking as if the type stores a value of type T.
Why do we need this in struct LockGuard? The type T is *const (), which is !Send + !Sync.
At first I thought it is to make LockGuard not Sendable and Syncable, but I'm not sure. Is it right?

**Comment by dubuduru** [comment]
Thanks. Then why do we implement Send or Sync for LockGuard?
In api.rs line 118-119:
`unsafe impl<'s, L: RawLock, T: Send> Send for LockGuard<'s, L, T> {}
unsafe impl<'s, L: RawLock, T: Sync> Sync for LockGuard<'s, L, T> {}`

**Comment by tomtomjhj** [comment]
hmm that's weird. `Sync` makes sense, but `Send` not in general. @jeehoonkang

**Comment by Lee-Janggun** [comment]
Doesn't Sync make sense when T is Sync? As I understand it, PhantomData is there to prevent LockGuard being derived as general Send and Sync, and the impl is there to make it available for special cases.

**Comment by Lee-Janggun** [comment]
Ok, I did some searching, and this is actually a pretty interesting problem.

* Rust standard: `std::sync::MutexGuard` is specifically marked as [not `Send`](https://doc.rust-lang.org/std/sync/struct.MutexGuard.html#impl-Send-for-MutexGuard%3C%27_%2C%20T%3E). In Rust, this was decided as the inner pthread used [did not allow locks to be sent across threads](https://github.com/rust-lang/rust/issues/23465). Recently, Rust has improved its [synchronization primitives](https://github.com/rust-lang/rust/issues/93740) to not depend on pthread on **most** platforms. Now does this suggest `MutexGuard` may become `Send`? Unfortunately, (1) the improved implementations may still be restricted to the same limitations (2) some platforms still depends on pthread, and (3) this it is a breaking change, hence this will most likely never become `Send`.
* Our situation: Then since we do not depend on any `pthread`, can we implement `Send`? The answer I think is yes. In `parking_lock`, [we can see that it is indeed `Send`](https://github.com/Amanieu/parking_lot/blob/9e956adc2c6ecde7c15ff7611396d24be711c8a9/lock_api/src/mutex.rs#L687-L696), which is possible because they implement their own locks. As we are also implement our own locks, I think having `Send` for our locks should be Ok.

**Comment by dubuduru** [comment]
Thank you so much! Now I see the point.
