### ISSUE TITLE
[Question] About NUMA awaring of MCS lock

### ISSUE THREAD

**Issue by jonge-1124** [kaist-cp/cs431#673]
While lcok function of ChlLock spins over node which was allocated by other thread, 
lock function of McsLock spins over self-allocated node. 

I've understood that's how McsLock considers NUMA.

However, I think that unlock function of McsLock has to spin over next node which was allocated by other thread. 
Then, does McsLock get advantage of NUMA consideration on its lock function, but get some trade-off on its unlock function?

**Comment by Lee-Janggun** [comment]
> I think that unlock function of McsLock has to spin over next node which was allocated by other thread. Then, does McsLock get advantage of NUMA consideration on its lock function, but get some trade-off on its unlock function?

For this, are your asking if it is not NUMA aware in `unlock()` because it waits on `(*node).next`? I am not an expert on this field, but in this case, I don't think it is a problem because the value we keep on reading is a field of `node`, which was allocated by the unlocked thread.

The only time the unlocked thread will access an allocation by another thread is [here](https://github.com/kaist-cp/cs431/blob/main/src/lock/mcslock.rs#L76). Since this access only happens once, I think it is ok.

Now as I said, I'm not an expert on this so I don't know if my answer above is correct. Also, it is not the intend of this course to know such details, so we will not ask such detailed NUMA questions other than what is mentioned in the slide.
