### ISSUE TITLE
[Question] Reason that `Lock<T>: Sync` requires `T: Send` & Exact meaning of `Send` marker

### ISSUE THREAD

**Issue by metamon123** [kaist-cp/cs431#675]
In several documents, an explanation for a meaning of `Send` marker is as follows:

1. slide 34p
> Send: transferable to other thread

2. https://doc.rust-lang.org/std/marker/trait.Send.html
> Send: Types that can be transferred across thread boundaries.

3. https://doc.rust-lang.org/book/ch16-04-extensible-concurrency-sync-and-send.html#allowing-transference-of-ownership-between-threads-with-send
> The Send marker trait indicates that ownership of values of the type implementing Send can be transferred between threads.

4. https://doc.rust-lang.org/nomicon/send-and-sync.html
> A type is Send if it is safe to send it to another thread.

All of the above explanations says that `Send` is related with "transferring something(value) to other thread".
Especially, 3rd document gives the most detailed explanation, which describes `transferring "ownership of values"`.

Now, let's see the [cs431 lock api](https://github.com/kaist-cp/cs431/blob/main/src/lock/api.rs#L37).

Based on the interpretation focusing only on "transferring of ownership", I thought that `Lock<L, T>: Sync` doesn't require `T: Send` because multiple references of `Lock<L, T>` from different threads don't change/transfer ownership of inner data `T`
```rust
// AS-IS
unsafe impl<L: RawLock, T: Send> Sync for Lock<L, T> {}

// Can we remove `T: Send` like this?
unsafe impl<L: RawLock, T> Sync for Lock<L, T> {}
```

However, according to many rust concurrent APIs, my thought seems like wrong. For example, [std::sync::Mutex](https://doc.rust-lang.org/std/sync/struct.Mutex.html#impl-Sync-for-Mutex%3CT%3E) also requires `T: Send` for `Mutex<T>: Sync`.

-> Q1. Why can't we remove the constraint `T: Send` for `Lock<L, T>` or `Mutex<T>` to be Sync?

After some investigations, I found [another interpretation](https://users.rust-lang.org/t/why-impl-sync-for-mutex-requires-t-send/12111/6) about a definition of `Send`, which regards not only "ownership" but also "mutable reference" of value as something to be transferred.

-> Q2. If a type is `Send`, should both an "ownership" and a "mutable reference" of value be transferable to other thread?

Thanks in advance!

**Comment by Lee-Janggun** [comment]
> multiple references of Lock<L, T> from different threads don't change/transfer ownership of inner data T

This is false. The entire point of having `Lock<L,T>` having multiple references is to transfer ownership of the inner data `T` from one locking thread to the next. Hence if the ownership cannot be safely shared, it should not be lock-protected. 

Now, there are a lot of explanations and somewhat ambiguity `Send` and `Sync`, and these trait bounds can be a bit weird. The best way to reason about why some bounds **are necessary** can be done by constructing a counterexample, as I will do below.

> Q1. Why can't we remove the constraint T: Send for Lock<L, T> or Mutex<T> to be Sync?

Consider a type that is **not** `Send`, the non-atomic [reference counted type](https://doc.rust-lang.org/std/rc/struct.Rc.html#impl-Send-for-Rc%3CT%3E), and consider what happens if `Lock<L,Rc<Vec<usize>>> : Sync`.

We can create a use-after free with two threads as follows.

1. Thread 1 creates a `rc1 : Rc<Vec<usize>>`, allocating the inner `Vec`, and creates a clone of it, `rc2`, increasing the inner reference count to 2.
2. Thread 1 puts `rc2` inside a lock `rc_lock : Lock<L,Rc<Vec<usize>>>`, and sends a reference it to thread 2, since it is `Sync`.
3. Thread 2 acquires the lock for `rc_lock` with the obtained reference, and has access to `rc2`.
4. Thread 2 tries to clone `rc2` to `rc3`. 
5. At the same time, thread 1 tries to clone `rc1` to `rc4`. Since thread 1 is not a `lock()`ing thread on `rc_lock`, there is a data race between the two clones. In the resolution of this race, the inner reference count only goes to up 3, but there are 4 references.
6. Thread 2 drops `rc3`, decreasing the reference count to 2. Then, it releases `rc_lock`.
7. Thread 1 drops `rc1` and `rc4`, decreasing the reference count to 0, running the destructor for the inner `Vec<usize>`.
8. Thread 1 obtains `rc2` back from `rc_lock`, and access the inner `Vec<usize>`. Use-after-free!

> Q2. If a type is Send, should both an "ownership" and a "mutable reference" of value be transferable to other thread?

This is essentially asking if `&mut T: Send` if `T : Send`. Unlike showing that a trait bound is necessary, showing that a bound is **sufficient** does require some concrete explanation. For that, please check see https://github.com/kaist-cp/cs431/issues/674#issuecomment-1279307214.

**Comment by metamon123** [comment]
Thanks for your detailed answer!

>> multiple references of Lock<L, T> from different threads don't change/transfer ownership of inner data T

Before all, I want to fix this sentence from the first comment. I wanted to say multiple "immutable" references instead of multiple references. (referring to a meaning of `Sync`)

> The entire point of having Lock<L,T> is to transfer ownership of the inner data T from one locking thread to the next.

Is it also true when there are only inter-thread immutable references? I think we don't move ownership if we only have immutable reference to the lock, and [cs431 lock api](https://github.com/kaist-cp/cs431/blob/main/src/lock/api.rs) don't provide interface to get ownership from immutable reference. Am I missing something?

> We can create a use-after free with two threads as follows. ...

On the otherhand, I think I got the point thanks to your example. My understandings are as follows:
1. Even though the other thread only has immutable reference to the shared value, some mutable actions in lower layer may be still possible. (ex. Incrementing Rc's inner reference count by `Rc::clone(&self)`)
2. In some cases, this will not make problem. In the above example, if all cloning actions of Rc in thread 1 is also done after acquiring rc_lock, I guess the Rc's inner reference count will not be broken.
3. But, because it's hard for API to consider specific usages like 2, API only assures `T: Send` -> `Lock<T>: Sync`. (Kind of soundness..?)

Let me know if there are some misunderstandings!

**Comment by Lee-Janggun** [comment]
> Is it also true when there are only inter-thread immutable references?

In rust, you cannot have multiple mutable references (`&mut`). So when you said "multiple references", it means multiple "immutable references".

> Is it also true when there are only inter-thread immutable references?

Well, yes. In the `RawLock` API, this ownership is represented as `Token`. In the `Lock<L,T>` API, this is represented as `LockGuard<L,T>`. If we have ownership of a, `LockGuard<L,T>` we have ownership of the inner `T` by the [deref traits](https://github.com/kaist-cp/cs431/blob/f23ffc5d1def1bdb27bcb1c244b170af395be02d/src/lock/api.rs#L140-L157), which allows us to access `T`.

> But, because it's hard for API to consider specific usages like 2, API only assures T: Send -> Lock<T>: Sync. 

Yes this is true. In order for a type system to claim it is sound, if a program is type-checked, no matter what you do in safe Rust, no undefined behavior should happen. Thus trait bounds must be conservative as possible.

**Comment by metamon123** [comment]
Thanks! Your answer helped me a lot. 👍
