### ISSUE TITLE
[Question] Why do we need token structure in ClhLock?

### ISSUE THREAD

**Issue by dubuduru** [kaist-cp/cs431#676]
In clhlock.rs, we define a struct that only contains a pointer.
```rust
pub struct Token(*const CachePadded<Node>);
```

And we use this struct in lock and unlock function.

But I wonder why we need this sturct; why don't we just use const* CachePadded<Node> as token type?

**Comment by tomtomjhj** [comment]
It's technically not necessary, but it is good for encapsulation, is more descriptive, and yet doesn't incur runtime overhead.

Encapsulation: If you use `*const CachePadded<Node>` directly, rustc will complain as follows:
```
error[E0446]: private type `clhlock::Node` in public interface
  --> src/lock/clhlock.rs:34:5
   |
7  | struct Node {
   | ----------- `clhlock::Node` declared as private
...
34 |     type Token = *const CachePadded<Node>;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak private type

For more information about this error, try `rustc --explain E0446`.
```
`Node` is private because users of clhlock doesn't need to and should not care about the implementation detail. What users need is just a token type, details of which doesn't matter for the users. Wrapping `*const CachePadded<Node>` in a struct hides such details and prevents users from accessing the implementation detail (and break the internal invariants).

**Comment by dubuduru** [comment]
I see, thank you for answering!
