### ISSUE TITLE
[Question HW3?] difference between x and ptr::read(&x)

### ISSUE THREAD

**Issue by Meraroo** [kaist-cp/cs431#681]
Implementation in drop function

when I wrote the code with ptr::read like

...
let next = ptr::read(&node.next);
let x = next.lock();
(use x)

successfully pass the test case but

...
let x = node.next.lock();
(use x)

returns the error message: 
/cs431/homework/target/debug/deps/list_set-e69c4e1bd21433e2` (signal: 11, SIGSEGV: invalid memory reference)

Now, I solved this problem in totally different way.
(I don't think this question is really about hw3)
But I'm still curious about the difference between
x and ptr::read(&x)

**Comment by Lee-Janggun** [comment]
That is really weird. Normally, using `ptr::read()` without being sure of what you are doing will lead to more errors. For this particular case, I have no idea why it happened without more information.

In terms of the difference between `x` and `ptr::read(&x)` as an rvalue in assignment, the first _moves_ `x` into the variable in the lvalue, while the latter creates a _bitwise copy_ of the `x` to the variable in the lvalue, but `x` is still alive. In particular, both `x` and the variable which `ptr::read(&x)` will have ownership of the same memory location.

Because of this, naively using `ptr::read(&x)` without properly dealing with the extra ownership is a formula for double-free, as indicated by the following innocent looking example.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=6c9f428086af10ce37f168b5d4d40ef9
```rust
use core::ptr;

fn main() {
    // Create a _immutable_ vec.
    let vec_1 = vec![1, 2, 3, 4];

    // Copy ownership into a _mutable_vec.
    let mut vec_2 = unsafe { ptr::read(&vec_1) };

    // Change the 3rd value.
    vec_2[2] = 45;

    // Note two things:
    // 1) We can still access vec_1, even though vec_2 has ownership for the location.
    // 2) The value of vec_1 changed!
    for i in vec_1 {
        println!("{}", i);
    }

    // Frees vec_1 and vec_2. Hence, the underlying buffer for the vector is freed twice, resulting in double free.
}
```

A **correct** usage of `ptr::read()` can be seen in the [stack implementation](https://github.com/kaist-cp/cs431/blob/main/src/lockfree/stack.rs#L76-L87). Note the usage of `ManuallyDrop`, which guarantees that the old copy of the ownership will not be dropped.

**Comment by Meraro** [comment]
I'm sorry for late reply.
Can I send you an e-mail about my own code?
By the way, the appropriate way of using ptr::read() is really helpful!
Thank you for your advice

**Comment by Lee-Janggun** [comment]
@Meraro Do you want to send me an email to ask about this? Sure, I'll take a look.

**Comment by Meraro** [comment]
It may be related to [@645](https://github.com/kaist-cp/cs431/issues/645)
