### ISSUE TITLE
Should T implement Send in Treiber's stack?

### ISSUE THREAD

**Issue by choejms** [kaist-cp/cs431#684]
Hi, 
In Treiber's stack, shouldn't T implement Send?
I think it is omitted in the github code.

**Comment by Lee-Janggun** [comment]
No, we don't need it. It's actually already inferred. As the [the documentation](https://doc.rust-lang.org/std/marker/trait.Send.html) says, `Send` and `Sync` are automatically inferred when the compiler can determine it, i.e, when all the fields are `Send` and `Sync` for some condition. Since all the fields of `Stack<T>` are `Send` when `T : Send`, `Stack<T> : Send` can be inferred. This is the reason we can do [this test case](https://github.com/kaist-cp/cs431/blob/357516babf0067e8e9592145e2a46536aaf3bd54/src/lockfree/stack.rs#L111-L126) in, if we had to manually implement `Send` and `Sync`. This test case will not even compile.

Now on the other hand, we can see that if you try to create a stack for a type that is **not** send, e.g, `Stack<Rc<i32>>`, we get a compile error.
```rust
fn push() {
        let stack = Stack::new();

        scope(|scope| {
            for _ in 0..10 {
                scope.spawn(|| {
                    for i in 0..10_000 {
                        stack.push(Rc::new(i));
                        assert!(stack.pop().is_some());
                    }
                });
            }
        });

        assert!(stack.pop().is_none());
    }
```

```
error[E0277]: `Rc<i32>` cannot be shared between threads safely
   --> src/lockfree/stack.rs:117:23
    |
117 |                 scope.spawn(|| {
    |                       ^^^^^ `Rc<i32>` cannot be shared between threads safely
    |
    = help: within `stack::Node<Rc<i32>>`, the trait `Sync` is not implemented for `Rc<i32>`
    = note: required because it appears within the type `ManuallyDrop<Rc<i32>>`
```

Normally, trying to implement your own `Send` and `Sync` can be a fatal error if you aren't really sure of what you are doing, so it's best to let the compiler do it on its own.

Now, one wants to implement `Send` and `Sync` on for a struct when **the fields do not implement them**, i.e, they are raw pointers, but the implementor is sure to provide enough synchronization for that pointer so that the trait bounds are actually Ok.

**Comment by kingdoctor123** [comment]
I'm sorry to kick in the discussion, but I guess Stack<T> should implement `Send+Sync` even if T has only `Send`, since data in the stack will not be accessed concurrently. So, I think explicitly implementing such rules is necessary, isn't it?

**Comment by Lee-Janggun** [comment]
Ah yes, you are right. Done in https://github.com/kaist-cp/cs431/commit/6dc501281b4952ead1e2ad9304033f83d1031d72. It was actually already there for the queue, but for some reason just missing for the stack...

**Comment by choejms** [comment]
Thank you for the explanation. I was asking if we should have `Stack<T, T: Send>` and now my question is resolved.
Thank you!

**Comment by Lee-Janggun** [comment]
Another type you have seen with a similar API is the [`Sender`](https://doc.rust-lang.org/std/sync/mpsc/struct.Sender.html#impl-Send-for-Sender%3CT%3E) type, which also has `impl<T : Send> Send for Sender<T>`. Here, making a `Sender<T>` itself does not require `T: Send`, hence you can make `Sender<Rc<usize>>` and use it for communication within the same thread. 

However, if you want to do inter-thread communication, you will ned to `Send` it to another thread using `thread::scope` and `thread::spawn`, which will enforce `T: Send` there.
