### ISSUE TITLE
[Question HW3] `Cursor::find` get `null` value

### ISSUE THREAD

**Issue by DaeyongKwon98** [kaist-cp/cs431#686]
I find that in `Cursor::find`, `*self.0` is null, so I get `invalid memory reference`.
In `OrderedListSet::find`, I define `cursor` and call `Cursor::find` like this.
```rust
let cursor = Cursor(self.head.lock().unwrap());
cursor.find(key)
```

So it means my defined `cursor` have nothing in it, but I don't know why `cursor` I define becomes `null`.
Is there any problem while defining cursor, or using `find` function?

Thank you.

**Comment by Lee-Janggun** [comment]
Your `OrderedListSet::find` seems fine, so its probably an issue with `Cursor::find()`.

In `Cursor::find()`, I think that if the list is empty, the raw pointer protected by the mutexguard can be null, since there are no nodes at all. I recommend you use [`ptr::as_ref()`](https://doc.rust-lang.org/std/primitive.pointer.html#method.as_ref) to just not worry about accidental null pointer access. e.g, have the following in `Cursor::find()`.
```rust
let option_node : Option<&Node<T> = (*self.0).as_ref();
<do stuff with option_node>
```

**Comment by DaeyongKwon98** [comment]
Using `as_ref` solves the problem, but another problem arises...
New problem is not about null value, so I will treat it at another issue.
Thank you.
