### ISSUE TITLE
[Question HW3] memory leak with `insert`

### ISSUE THREAD

**Issue by DaeyongKwon98** [kaist-cp/cs431#689]
Now I just try test case: insert(1) and check with `cargo_asan test --test list_set`.
It says `24byte(s) leaked in 1 allocation(s).`
When I try insert() for n times, there are memory leak from n locations.
I think memory leak is due to `drop`, but it's not `OrderedListSet::drop`. Is it right?
(Now I make `Iter::next` and `OrderedListSet::Drop` to `todo!()`

In `insert`,
I define `cursor` with `find`, and do
`*cursor.0 = Node::new(key,*cursor.0)`
(There's no `drop` in `insert`)

In `Cursor::find`, I `drop` `(*self.0).as_ref()` after doing
`*self = Cursor(node.next.lock().unwrap())`

I read #210 , but I can't find why my memory leak occurs..

Also I have confusion about what to `drop`.
For example, I confuse with which one is right among
drop(Node<T>), drop(*mut Node<T>), drop(MutexGuard).

**Comment by DaeyongKwon98** [comment]
I change drop(node_ptr) to drop(Box::from_raw(node_ptr)), and somehow it works.

**Comment by Lee-Janggun** [comment]
Ah... those two operations are very two things.

# `drop`ing a raw pointer (`drop(node_ptr)`).

In terms of memory deallocation, dropping a raw pointer essentially does nothing, because a raw pointer is just keeps a reference to memory, and in itself does not indicate ownership linked to `node_ptr`.

# `drop`ing a `Box` (`drop(Box::from_raw(node_ptr))`)

Here, `Box::from_raw` returns the ownership related to `node_ptr`. Hence, dropping the result will actually deallocate the related resource.
