### ISSUE TITLE
[Question] First push into empty Michael-Scott's queue

### ISSUE THREAD

**Issue by Allgot** [kaist-cp/cs431#700]
Hello.

I want to clarify the process of pushing the first element into the empty MS queue, then checking it is empty or not in succeeding 'try_pop' function.

At first, the queue might look like
```
head: data-X, next-null
tail: data-X, next-null
```

And if we perform the 'queue.push(3)', it will be look like
```
head: data-X, next-null
tail: data-3, next-null
```

However, then the next 'queue.try_pop()' will return None, and this is a nonsense.

So I think at the first 'push' function, it should change the queue like
```
head: data-3, next-null
tail: data-3, next-null
```
That is, head is the same as the tail. Is this right?

If so, is it according to the fact that both of the head and the tail store the same node named sentinel in the default definition of queue? In other words, following codes do not mean the copying the sentinel node?
```
q.head.store(sentinel, ~~)
q.tail.store(sentinel, ~~)
```

**Comment by choejms** [comment]
Initially, head and tail point to the same dummy node. Sentinel's next is null. 
```
   +--------+                    +--------+            +---------+
    |      tail     |      -->         | sentinel |    <--    |    head    |
    +--------+                    +--------+             +---------+
```

In queue.push(3), we have a CAS between tail's next (which is Null) and the new node. So we have the following.
```
   +--------+                    +--------+            +---------+
    |      tail     |      -->         | sentinel |    <--    |    head    |
    +--------+                    +--------+             +---------+
                                                 |
                                                 v
                                         +---------+
                                         |       3        |
                                         +---------+
```
In 'queue.try_pop()', we have a CAS between head (which points to sentinel) and next (which is 3). So head points to 3. And we return next_ref's data which is 3. And by using guard, we drop sentinel later. 

```
   +--------+                    +-------+            +---------+
    |      tail     |      -->         |     3      |    <--   |    head    |
    +--------+                    +-------+           +---------+
                                                
                                          
```

So from now, 3 acts like the sentinel. We cannot access 3 using operations like try_pop() because try_pop() always returns sentinel's next value. 

And you are right in saying sentinel is not copied in 
```
q.head.store(sentinel, ~~)
q.tail.store(sentinel, ~~)
```
This is my version of understanding. 
If my explanation is wrong, please correct me.

**Comment by Lee-Janggun** [comment]
@choejms 's explanation is correct :)

In MS-queue, we always have one sentinel node so that we can maintain the invariant that the node tail pointer points to is reachable from the head. That's why in the implementation of [`Drop`](https://github.com/kaist-cp/cs431/blob/6dc501281b4952ead1e2ad9304033f83d1031d72/src/lockfree/queue.rs#L175-L188) for the queue, we additionally deallocate the sentinel node in addition to calling `try_pop`.

**Comment by Allgot** [comment]
Thanks for detailed example and additional comments. I appreciate it!
Now I understand how this MS queue work!
