### ISSUE TITLE
[Homework 6] Meaning of "pointer to `free::<T>`" 

### ISSUE THREAD

**Issue by choejms** [kaist-cp/cs431#704]
Hi,

In retire.rs, the comment for struct RetiredSet says "the second value is the function pointer to `free::<T>` where `T` is the type of the object."

But what is the meaning of "pointer to `free::<T>`" and why is it necessary?
I first thought there would be a struct called `free`, but there is not struct declared as `free`.

My second question is that inside `fn retire()` we have a declaration of `fn free<T>`, but I am wondering why `fn free<T>` is declared inside `fn retire()` instead of `fn collect()`, since we are freeing the data in `fn collect()` and not in `fn retire()`

Thank you

**Comment by choejms** [comment]
I think I understand the meaning of the function pointer now

**Comment by Lee-Janggun** [comment]
Oh ok nice! I'll leave an answer anyway to make sure that your understanding is the same as mine and anybody that sees this issue at a later stage understands it as well.

Hazard Pointers store retired pointers in their machine representation (`usize`) without type information. Hence when we try to actually free them, we cannot determine the type of the pointer being freed. 

Since we must have this type information somewhere to be able to call the proper destructor for the pointer, we build a deallocation function in `retire()`, where we know about the pointer we are trying to free.

This is evident on how the functions are parametrized. `retire()` is parametrized by `T`, but `collect()` is not parametrized by any time. 

For a possible additional question on why don't we just make the hazard pointer parametric on `T`, its because we want to be able to support multiple pointers of different types with one hazard pointer instance.

**Comment by choejms** [comment]
Thank you for the explanation! It helps me understand the purpose better.
