### ISSUE TITLE
[Homework 6] Double free error in collect()

### ISSUE THREAD

**Issue by choejms** [kaist-cp/cs431#705]
Hi, I am getting a double-free error, and I think it's due to the fact that different threads retire a pointer that points to the same object.

Since each thread keeps its own `RetiredSet`, I don't think there is any way for one thread to check that other threads have not retired the pointer to the same data. Are there any tips on this problem?

**Comment by tomtomjhj** [comment]
>  different threads retire a pointer that points to the same object.

This shouldn't happen in the first place. Users of hazard pointers can retire a pointer only if they are *the* one who detached the memory block from a shared data structure. 

Even if you made sure that this doesn't happen, then something else if wrong.

**Comment by Lee-Janggun** [comment]
As @tomtomjhj said, the task of not retiring the same pointer twice is the task of the hazard pointer API. For the tests cases we provided, we were sure of this.

What may be happening is that when a thread calls `collect()` and checks the current list of protected pointers, the current set of current protected pointers was incorrectly obtained, and did not include a pointer that was protected.

I recommend you go over the implementations for `HazardBag`

**Comment by choejms** [comment]
Hi, thank you for the explanation.

Also, I am wondering how to deal with the case when hazardbag is updated while `collect()` is being executed. For example, while thread 1 is reclaiming pointers that are not in the hashset, it may be that other threads are protecting the pointers that point to the same data. Is this also not possible on the API level?

**Comment by Lee-Janggun** [comment]
That cannot happen, as if a pointer has been retired, it has must have removed from shared memory, hence it cannot be the case that it is newly protected (this is precisely why the hazard pointer algorithm has validation in the protection step).

> What may be happening is that when a thread calls collect() and checks the current list of protected pointers, the current set of current protected pointers was incorrectly obtained, and did not include a pointer that was protected.

Also I realized that this explanation is wrong, since in our implementation, only a thread that retired the pointer should be able to free it. What might be the case is that you put the freed pointer back in the retire set afterwards.

**Comment by choejms** [comment]
@Lee-Janggun Thank you for the explanation. 
You said a retired pointer cannot be newly protected due to validation in the protection step.

It is my understanding that validation step makes sure `src (AtomicPtr)` points to `*pointer`,
but I am having a difficult time understanding why this is necessary.
Also, I do not understand the reason for updating `pointer` to the latest value. 

Could you give an example what would go wrong if we did not make sure `src` points to `*pointer`?

**Comment by Lee-Janggun** [comment]
@choejms Sorry for the extremely late reply.

The situation you are worried about (try_protect returns true for a retires _and freed pointer_) should not happen because a pointer is retired while before validation, then validation will fail. And if validation succeed before retirement, then the pointer will not be freed.

...or so one may think.

This is true for the case for DSs such as Treiber's stack where we only need to protect the pointer for the head node pointer by the stack pointer. 

For Micheal Scott's queue, we need to protect both the head and next node, and validations of the next node must be taken with care (details will be dealt in the lecture). One can argue that `try_unprotect` should be marked as unsafe to deal with this case. We are updating the homework with MSqueue to more clearly display this fact.

This a bit of a point of gray area for which functions are marked as unsafe, and I think that the fact that we use raw pointers to access the inner data makes it Ok that `try_protect` is marked as safe (like how `ptr::is_null()` is safe). That is, the user should have used the hazard pointer API correctly to get proper guarantees from it.

**Comment by Lee-Janggun** [comment]
We updated the hazard pointer homework to include a bit more detail in https://github.com/kaist-cp/cs431/commit/2468576b5520d0c64f7f9d75296634269ccef259.
