### ISSUE TITLE
[Lecture] guard in load instructions

### ISSUE THREAD

**Issue by mouna77** [kaist-cp/cs431#727]
Hello!
I was going through the implementations of the lists, and I saw that sometimes we use a guard for load sometimes not. And the guard is sometimes used to pin the thread:  `let guard = crossbeam_epoch::pin();` , sometimes it's just an unprotected guard : `let guard = unsafe { unprotected() };`
I understand that the difference between the two guard definitions is that the first one pins a thread. But why do we need to do that? And why is it not used in every `.load(Ordering::....)` ?

**Comment by Lee-Janggun** [comment]
In crossbeam's EBR mechanism, one pins a thread to notify that there is an active thread, hence objects that this thread may access with the obtained guard may not be retired.

In theory, one can just use this guard everywhere. However in situations where one is sure that the data it will access is not shared (e.g, constructors) there is no worry about use-after-free, hence pinning will simply be an overhead. In such cases, one can simply use an unprotected guard, which does not do pinning and makes retiring an object equal to freeing it immediately.

Now, depending on how one uses the guard, it may be that one has to use a pinned guard, even in a single thread situation. An example is our lockfree list. In the implementation of lookup and delete, the returned value's reference is tied to that of the guard, ensuring that it stays alive as long as the guard stays alive. Using an unprotected guard (which has a static lifetime) breaks this assumption since retiring means immediate freeing, hence may lead to use-after-free.

**Comment by mouna77** [comment]
okay I see. It's a matter of how we plan on retiring the objects.
