### ISSUE TITLE
[Question] Function of memory ordering

### ISSUE THREAD

**Issue by choejms** [kaist-cp/cs431#733]
Hi 
I am confused by the function of memory ordering.
In my understanding, we use memory ordering (Acquire/Release) to synchronize the views of different threads.
But another function of Acquire is to prevent the memory reordering such that codes below Acquire statements cannot move up the Acquire statement. 

I am wondering if these two functions are related and if so what is their relationship?
To be more speicfic, how does preventing memory reordering lead to synchronization of views?

The second question is is using Acquire only meaningful if we use it together with Release?

**Comment by tomtomjhj** [comment]
> I am wondering if these two functions are related and if so what is their relationship?
> To be more speicfic, how does preventing memory reordering lead to synchronization of views?

Those are two different but mostly equivalent ways to understand semantics of memory ordering.
The view-based model is suitable for high-level reasoning about the programs you write, while the reordering-based model is suitable for implementing compiler/hardware.
It's safe to reason about your program in the view-based model, because the observable behaviors of a program considered in the view-based model are included in the behaviors considered in reordering-based model.

> The second question is is using Acquire only meaningful if we use it together with Release?

Yes

**Comment by Lee-Janggun** [comment]
To add a bit more explanation.

Your second explanation of limiting reordering is the reason compiler architects introduced such orderings. 

However, when defining a language semantics, its not ideal to make it depend on a certain optimization, because we want to prove optimization with respect to semantics, so we will have a logical loop if that were the case.

Hence, an independent semantics is needed that is (1) independent of the notion of reordering (2) but still forbid them when trying to apply them as optimizations. The "view semantics" is an attempt at such semantics, in a operational manner. 

In terms of why the semantic works, since the semantics of acquire ordering requires it to update the current threads view to that of the release view, if some code was reordered up the acquire read, the view of the reordered code may become smaller than before, hence it is not a valid optimization.
