### ISSUE TITLE
[Question]question about pop in Treiber's stack

### ISSUE THREAD

**Issue by dripcharacter** [kaist-cp/cs431#745]
Now I am reviewing what I learned for final exam.
And I got some confusions about Treiber's stack.

In pop(), we got bitwise-copy(shallow copy) of h.data by `ptr::read(&h.data)`.
And I understood that since it is a just bitwise-copy, position of h.data is still in heap.
But while I reviewing my note, it says 'data move from heap to stack when `ptr::read(&h.data)`.'
But I think it is my misunderstood at that time. So my first question is
'does h.data moved to stack when `ptr::read(&h.data)`?'

Second question is about `ManuallyDrop::into_inner`.
In document of `ManuallyDrop::into_inner`, they says, 

> Extracts the value from the ManuallyDrop container.
>This allows the value to be dropped again.

Since into_inner is applied to bitwise-copy of h.data, I think h.data became T from ManuallyDrop<T>, too.(Since they are just shallow copy.)
If so, the reason why we used ManuallyDrop disappeared since h.data can be dropped without calling explicitly called drop.
If my understand is right, what prevent h.data from double free error?
Or if it is not, can you explain what happened when `ManuallyDrop::into_inner` applied to bitwise-copy of h.data?

**Comment by Lee-Janggun** [comment]
On a first note, for the purpose of this course, you really don't need to care about the detail of ManuallyDrop. They are just ways to have more fine-tuned control for ownership in Rust with very strict protocols. If you want a simple solution, Option<T> is the way to go.

With that being said, to answer your question...

> Does ptr::read move data from heap to the stack?

I don't think so as that would (a) be very inefficient, which is counterintuitive as the whole purpose of using ptr::read is to be efficient (b) the data may not even be in the heap in the first place.

The way I use ptr::read(src), as I have mentioned in the safety comments, is creating a copy of the ownership of memory src points to.

On why we use ManuallyDrop, ManuallyDrop, it is in the Rust language specification that when ManuallyDrop's destructor is called after it's lifetime is over, the inner value will not be dropped. The user must drop the inner value manually (hence the name). So double free here is avoided as the ManuallyDrop<T> inside the node being destroyed will not free the inner T.

**Comment by tomtomjhj** [comment]
related? #287

**Comment by dripcharacter** [comment]
I read #287 and @Lee-Janggun 's answer.
>the data may not even be in the heap in the first place. In the implementation at the codegen level it should just be retuning the address of the underlying data.

But I don't understand why data may not even be in the heap. Since we put node to stack by push and push uses Owned::new which uses Box internally, data must be in heap in the first place. Am I right?
By the way, I understood that ptr::read(&param1) just make copy of the ownership and don't move the param1.

For the second question, I made some example about ManuallyDrop::into_inner. (https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1441ac10fd0cda621347baceffad7b5f)
I was confused whether using into_inner make value loses the property of ManuallyDrop(prevent value drop when struct drops.) when I first asks the question but since field 'peach' didn't drop after dropping the FruitBox although I used into_inner to peach, I concluded that into_inner just extract the value, Am I right?

I got one more trivial question while I make example(https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e620ee0df4619be4c90eb0d243f8232d).
peach and tmp.peach have different value. But I think it was originated by using ptr::read to the type that didn't implemented Copy.
>If T is not Copy, using both the returned value and the value at *src can violate memory safety. (from https://doc.rust-lang.org/std/ptr/fn.read.html#ownership-of-the-returned-value)

Since Peach didn't implemented Copy, example code violated memory safety, Am I right?

**Comment by Lee-Janggun** [comment]
> But I don't understand why data may not even be in the heap.

What I meant was that in general, you don't know whether `src` in a call to `ptr::read(src)` points to the stack or heap. For our stack, yes it should be in the heap.

> I was confused whether using into_inner make value loses the property of ManuallyDrop(prevent value drop when struct drops.) 

Yes it does not make it lose this property. The purpose of `ManuallyDrop` is to allow for one to make the dropping of a field be independent of the dropping of the struct.

> https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1441ac10fd0cda621347baceffad7b5f

This example has use-after-free in general. If you are doing `ManuallyDrop::take` in the struct that contains it, there is no real point of using `ManuallyDrop`, since dropping the struct will drop the field as well. The reason no error happened here is because you used zero sized types which have nothing done when dropped. If, for example one of your field was `ManuallyDrop<String>`, you will get a [double-free error](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d4a1d53ad0802e3cb08bfd88cd650066).

> peach and tmp.peach have different value. But I think it was originated by using ptr::read to the type that didn't implemented Copy.

This is completely expected behavior. You created a bitwise copy of what was pointed by `&tmp.peach`, hence the struct `peach`. Changing one will not not change the another.

> Since Peach didn't implemented Copy, example code violated memory safety, Am I right?

In this case, no. yes you didn't implement `Copy` for peach, but the bitwise copy is `Copy` , so it is just missing a certain trait bound. Whether or not it is implemented will effect runtime behavior, and since your code that does implement `Copy` is memory safe, the code that did not implement `Copy` is also memory safe.

**Comment by dripcharacter** [comment]
Sorry for my shallow understanding, I have last question about bitwise copy.
(1)when object to copy not have reference(like data in Node), then bitwise copy makes object that has same bit but independent object from original object(Like modifying or drop copied object has no effect to original one.)
(2)when object to copy has reference field, then bitwise copy makes object that has same bit and dependent object from original object(if copied object drops, reference field in copied field is drop and this makes double-free error when drops original object)
(reference: https://stackoverflow.com/questions/42749439/what-is-the-difference-between-memberwise-copy-bitwise-copy-shallow-copy-and-d)
My understanding about bitwise copy is like that. Is that right?

**Comment by Lee-Janggun** [comment]
> (1)when object to copy not have reference(like data in Node), then bitwise copy makes object that has same bit but independent object from original object(Like modifying or drop copied object has no effect to original one.)

Yes, but with a few comments. What you need to mean by "reference" here if a type that represents something more then what its machine representation is (i.e, `Vec`, `String`, `Box`'s machine representation is a location to a heap it owns). In particular, since `data` field of `Node` is any type `T`, we can't say it does not have any reference. 

> My understanding about bitwise copy is like that. Is that right?

Yes, your understand is correct.

**Comment by dripcharacter** [comment]
Finally, I got good intuition!! Thank you
