### ISSUE TITLE
[Question] What is the meaning of critical read?

### ISSUE THREAD

**Issue by choejms** [kaist-cp/cs431#749]
Hi,
What is the meaning of critical read? And why is [read of head = null] in Treiber's stack an example of critical read?
I tried looking up in Google but there is no good description of critical read.

<img width="796" alt="스크린샷 2022-12-10 오전 5 33 42" src="https://user-images.githubusercontent.com/90259205/206791423-c5a7f9e7-110c-49b8-ac2d-7b1402e9e310.png">

**Comment by dripcharacter** [comment]
According to my understanding, critical read is a read operation that determines the result of operation.
If we read that head of Treiber's stack is null, at that point, result of pop operation determines to None since stack is empty.
According to definition about critical read in above, [read of head=null] is the critical read.
