### ISSUE TITLE
[Question] I still cannot understand causality test #19

### ISSUE THREAD

**Issue by Meraroo** [kaist-cp/cs431#758]
I read #753  but.. I think if thread 3 join()ed, then x will become 42. Why is this wrong?
I have one more question. If thread 1 doesn't have join thread 3, then r1=r2=r3=42 is possible?

**Comment by hotmandu** [comment]
I'm not sure about my reasonings, but here are my opinions anyway:
1)
In order to set `r1`, Thread 1 should wait for thread 3 to finish. In this case, `r3 = X` should read `0`, as no other thread can promise (and certify) the write `X = 42`. Note that we are checking `r1 = r2 = r3 = 42`, not `X = Y = 42`
2)
Let's say thread 3 promised `X = 42` write. Then with help of thread 1&2, `X = 42` can be written.
However if `r3 = X` reads `42` on thread 3, thread 3 doesn't write anything, which fails to certify the promise.
(I wonder if the the above case can be viewed as RW coherence like Causality test 16...)
