### ISSUE TITLE
[Question] Ordering in Linked List Delete

### ISSUE THREAD

**Issue by choejms** [kaist-cp/cs431#759]
`let next = curr_node.next.fetch_or(1, Ordering::Acquire, guard);`

Why is fetch_or Acquire in [L245](https://github.com/kaist-cp/cs431/blob/518270ed6e35132361a6dbc45c79a6801faf74ea/src/lockfree/list.rs#L245).

I think it should be AcqRel because when fetch_or is performed, the logical deletion should also be visible to other threads that are trying to logically delete the same node. 

Thank you in advance.

**Comment by hotmandu** [comment]
I've searched about 'relaxed RMW' and got these stackoverflow answers. I'm not sure these are relevant, but I'll share the links:
1. [How does mixing relaxed and acquire/release accesses on the same atomic variable affect synchronises-with?](https://stackoverflow.com/questions/71509935/how-does-mixing-relaxed-and-acquire-release-accesses-on-the-same-atomic-variable)
2. [What does "release sequence" mean?](https://stackoverflow.com/questions/38565650/what-does-release-sequence-mean)

**Comment by dubuduru** [comment]
In my opinion, Acquire is enough. In fact I thought Relaxed ordering is possible, but becuase of [L252](https://github.com/kaist-cp/cs431/blob/518270ed6e35132361a6dbc45c79a6801faf74ea/src/lockfree/list.rs#L252), Acquire is needed..

The reason I thought Relaxed is enough is that, as fetch_or is RMW, any thread that executes fetch_or reads latest value regardless of ordering. So it can know whether the node is logically deleted or not.
However, Acquire is needed because we should know the "Released" view of the pointer to satisfy the invariant of queue. By Acquire, we get the released view, and in cas of L252, we release this view to maintain invariant.

This is what I think.
If you think there's somting wrong, please tell me!

**Comment by choejms** [comment]
Aha that makes so much sense Thank you !!
