### ISSUE TITLE
[Question] HW2: Why are we using mem::swap / mem::replace ? 

### ISSUE THREAD

**Issue by quanxi1** [kaist-cp/cs431#831]
```
    pub fn append(&mut self, other: &mut Self) {
        if self.tail.is_null() {
            mem::swap(self, other);
        } else {
            let other_head = mem::replace(&mut other.head, ptr::null_mut());
            //let other_head = other.head;
            //other.head = ptr::null_mut();       <- Why don't we do this instead? 
            if !other_head.is_null() {
                unsafe {
                    (*self.tail).next = other_head;
                    (*other_head).prev = self.tail;
                }
                self.tail = mem::replace(&mut other.tail, ptr::null_mut());
                self.len += mem::replace(&mut other.len, 0);
            }
        }
    }
```

Hello, I've got a question while doing my homework 2.
For the line `let other_head = mem::replace(&mut other.head, ptr::null_mut());`, why can't we substitute it with the commented lines? I'm curious about what's the benefit of using them. Thank you!

**Comment by Lee-Janggun** [comment]
`mem::replace` can be used to replace the value in the case the inner value doesn't implement `Clone`. In your example, the reason your code works is because raw mutable pointers implement `Copy` (hence implements `Clone`), so `let other_head = other.head;` will copy `other.head` into `other_head`.

If you try it with a type that doesn't implement `Copy`, you will get a compile time error, as in the following example.

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a97a8f9a017489e43f2e14d6b9c54ad8)
```rust
#[derive(Default)]
struct Temp;

#[derive(Default)]
struct Wrapper(Temp);

fn f() {
    let a = &mut Wrapper::default();
    let _b = a.0;
    a.0 = Temp::default();
}
```

For more information, please see [the docs for `mem::replace`](https://doc.rust-lang.org/std/mem/fn.replace.html#examples)
