### ISSUE TITLE
[Question] Why the name of the method is try_pop() not pop() in lock free queue?

### ISSUE THREAD

**Issue by 33577** [kaist-cp/cs431#855]
Hi, 
I wonder why the name of the method is `try_pop()` not `pop()` in lock free queue.

I've considered a few reasons but haven't landed on a solid explanation.
- For the `None` value, it is natural operation when queue is empty in `pop()` API.
- I can't see any possibility of failure in this method.
- Is it for noticing non-blocking API? But why we need to expose it?

Thanks!
https://github.com/kaist-cp/cs431/blob/main/src/lockfree/queue.rs#L123

**Comment by tomtomjhj** [comment]
I think calling it `pop` is fine. 

However, due to weak memory effect, `unsafe { head.deref() }.next.load(Ordering::Acquire, guard)` may read a stale value (we usually cover weak memory semantics, but we didn't have time this year). So try_pop may return None even if a new node is appended. That's one reason you may want to call it `try_pop`, but I think the name doesn't really matter.
