### ISSUE TITLE
[Question] Readings for Further Studies

### ISSUE THREAD

**Issue by prime235711** [kaist-cp/cs431#862]
While I was reading the multiprocessor programming book to study for the final, I found that there are more materials that we didn't covered in class due to the lack of time, or that we only skimmed through, like skiplists and work-stealing queues.

I want to hear about why did you selected these materials among all bunch of concepts in concurrency. And what chapters do you recommend us to read? Are there any other materials that are good for followups(e.g. books/papers)?

**Comment by jeehoonkang** [comment]
Hi @prime235711,

Thank you for your interest in the course.

I didn't study concurrency and parallelism through the traditional "art" book or standard curriculum, which is why your TA @tomtomjhj often points out my lack of basic knowledge in this area and urges me to study more ("교수님 공부좀 하세요"). Instead, I learned about concurrency "on the streets" by reading and writing papers. This approach has its advantages and disadvantages, both for me as an independent researcher and as the instructor for this course. Although this course's learning path is unconventional, I believe it ultimately proves beneficial.


When selecting topics for the course, I considered three criteria:

- **Relevance**: I chose topics that are likely to be pertinent to your future career.

- **Effectiveness**: I focused on topics that are challenging to learn independently but are more accessible with an instructor’s guidance. Learning these materials on your own might have been too difficult.

- **Efficiency**: I aimed to cover as much material as possible in a single semester, which is why I excluded certain topics like relaxed behaviors or advanced data structures such as skip lists.


Over time, my understanding of concurrency and parallelism has deepened, leading to changes in the course content. This semester's curriculum is a carefully curated list based on my current insights. I plan to make more significant changes in future semesters.

I'm satisfied if the theory you've learned is useful for your career. For most career paths, further study in concurrency isn't necessary. I'm particularly proud of this blog post: [https://channel.io/ko/blog/tech-backend-be-detective-office], which highlights how my course helped a student identify a concurrency bug. If you've developed a deeper interest in concurrency, I recommend reading the "art" book, my papers <https://www.fearless.systems/#publications>, or those by my Ph.D. supervisor Chung-Kil Hur <https://sf.snu.ac.kr/publist/>. While there are many excellent papers on concurrency, these are my personal favorites.

Best regards,
Jeehoon
