### ISSUE TITLE
[Question] (Concurrency Error on Ptr_Eq which is not todo()!)

### ISSUE THREAD

**Issue by Delulu-lu** [kaist-cp/cs431#882]
Hi, When I run 
cargo test --features check-loom --doc arc -- --nocapture --test-threads 1
I get an error in ptr_eq() which is not todo(). 
<img width="739" alt="Screen Shot 2024-03-09 at 17 59 49" src="https://github.com/kaist-cp/cs431/assets/160591381/8e223eda-70d4-4978-9713-816960ad7478">

**Comment by kingdoctor123** [comment]
Hello. Such error occurs since doctest (`--doc`) is not written for testing with loom. You can make a doctest for `ptr_eq` pass by doing the following stuffs:

1. Implement `clone` and `drop` functions of Arc (which are originally `todo!()`)
2. Change the [doctest](https://github.com/kaist-cp/cs431/blob/main/homework/src/arc.rs#L290-L297) for `ptr_eq` into the following:
```rust
/// use cs431_homework::Arc;
/// use loom::*;
///
/// loom::model(|| {
///     let five = Arc::new(5);
///     let same_five = Arc::clone(&five);
///     let other_five = Arc::new(5);
///
///     assert!(Arc::ptr_eq(&five, &same_five));
///     assert!(!Arc::ptr_eq(&five, &other_five));
/// })
```

Please note that doctest with loom is not done in actual grader (`grade-arc.sh`), so you don't need to worry. Test with loom is done only with `--test arc` option.

**Comment by Delulu-lu** [comment]
I pass all test cases in by loom with --test flag. But I have still some doubts about my implementation, I wonder if it is correct, as It claims all possible interleavings.

**Comment by kingdoctor123** [comment]
Passing all test cases with loom does not guarantee that your implementation is 100% correct. It only guarantees your code passes *the given test cases* in all possible interleavings, still leaving possibility of failure in other test cases. If you are unsure about your code, then you can think of complex test cases and run it. Probably this is suitable for our class.

In fact, to be 100% sure about your implementation, you can use a mathematical method called *formal verification*. This method allows you to prove perfect *absence* of bugs by precise reasoning based on some logics and language semantics. But this is clearly out of scope of our class.

**Comment by Lee-Janggun** [comment]
For this course, we will run the provided grade scripts for the final submission as well, so if your code passes the script, it should be fine.

**Comment by Lee-Janggun** [comment]
Closing, feel free to re-open if you have other questions on this issue.
