### ISSUE TITLE
[Question] Clippy "errors" in submission

### ISSUE THREAD

**Issue by thekioskman** [kaist-cp/cs431#894]
From my understanding - we are meant to fix clippy "errors" (warnings) for our code to to accepted into gg, however some of the errors are pretty restrictive.
![image](https://github.com/kaist-cp/cs431/assets/57548877/f5a0891a-2c1c-49aa-beb7-a437c3b26023)

For instance this is a warning on my local, but on the server it gives and error

**Comment by kingdoctor123** [comment]
Instead of disabling `clippy`, you can just follow the instructions by the `clippy` as @m-spitfire said. In most cases, you can easily modify the code with little effort so that it passes `clippy`. By doing so, you can write a better Rust code with reduced possibility of mistakes. 

For this reason, we enforce everyone to submit a solution that passes the `clippy`.
Related: https://github.com/kaist-cp/cs431/issues/606#issuecomment-1235141296 https://github.com/kaist-cp/cs431/issues/637#issuecomment-1254468805

**Comment by Lee-Janggun** [comment]
Please don't post images.

We also ask to fix clippy explicity, as seen on the last line on your image:

```
'Please fix the issues from `cargo +nightly clippy -- -D warnings` first.'
```
