### ISSUE TITLE
[Question] Comparison between `backoff.snooze()` and `std::hint::spin_loop()`

### ISSUE THREAD

**Issue by bonjune** [kaist-cp/cs431#920]
To implement a lock (other than parking locks), a thread should spin.
In the reference implementation, `backoff.snooze()` is used.
But when I change the backoff function to `std::hint::spin_loop()`, I observe the change of lock's behavior over the `smoke` test (https://github.com/kaist-cp/cs431/blob/main/src/lock/api.rs#L121-L144).
In most cases, it behaves exactly the same but _sometimes_ the test DOES NOT finish within 60 seconds.

```
running 1 test
test ticketlock::test_ticket_lock has been running for over 60 seconds
test ticketlock::test_ticket_lock ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 2 filtered out; finished in 71.41s
```
It seems like the backoff function doing a better job as I don't see cases taking longer than 0.5s.

Why?

---

+ I only used `SeqCst` for memory ordering

**Comment by kingdoctor123** [comment]
I'm not sure why you see the significant difference because `std::hint::spin_loop()` is merely a hint and architecture-dependent feature. But if you see the documentation for those functions and read the exact code, you can get some idea:
- `backoff.snooze()`: https://docs.rs/crossbeam/latest/crossbeam/utils/struct.Backoff.html#method.snooze
- `std::hint::spin_loop()`: https://doc.rust-lang.org/std/hint/fn.spin_loop.html

The implementation of `backoff.snooze()` not only calls `std::hint::spin_loop()` but also calls `yield_now()`, which explicitly yields the current execution of this thread to the OS and asks for OS to execute other threads to make progress. Since `std::hint::spin_loop()` is merely a hint to CPU and does not explicitly yields the execution of current thread, probably explicit blocking the thread was effective in your case. 

You can understand the situation with the following intuitive explanation (note that this may not be correct; this is just my thought). If one thread fails to acquire the spinlock, then immediate retry is highly likely to fail again. Instead, the thread is better to wait until another thread (the one holding the lock) to finish its task. Thus, using `backoff.snooze()` *might* be more efficient than using `std::hint::spin_loop()`.

**Comment by bonjune** [comment]
Thank you for your explanation!
