### ISSUE TITLE
[Lecture] Suggestion on teaching promising semantics 

### ISSUE THREAD

**Issue by BraSDon** [kaist-cp/cs431#949]
Promising semantics is a challenging topic to understand as we have seen by the amount of questions asked during the lecture. We even had to repeat the core aspects over multiple sessions. To improve understanding and lecture time I suggest allocating lecture time (e.g. 30 minutes) for individual reading of selected sections of the "A Promising Semantics for Relaxed-Memory Concurrency" paper.

**Why read the paper?**
Speaking from own experience, it helped tremendously with understanding the concepts. Mainly because the description of the aspects is precise, while being written in an easy to understand way. This combination of precise and easy to understand is hard to replicate with spontaneous speech during a lecture. Just think about how long it must haven taken to end up at the wording in the paper.

**Why allocate lecture time to reading the paper, can't students do that in their own time?**
Yes, they could do it on their own time. However, as we saw with other reading/watching assignments the amount of students actually doing them is rather low. Why should that be different during the lecture? I think because in this case students already allocated the time to focus on the topic, so they might as well use the time and read the paper instead of watching Spongebob. 

**But doesn't that take away valuable lecture time?**
I would argue no, because students will have less questions and don't require multiple session of repeating the same content. Therefore making up the time used for the individual reading. To be fair, it could also be that the questions will just be more advanced, however that means the overall understanding is better, which is ultimately the goal - getting the students to a high proficiency level.

 I wonder what your thoughts about this are @jeehoonkang @kingdoctor123 
 Thank you for considering my suggestion.

**Comment by kingdoctor123** [comment]
Thank you for your feedback. Jeehoon and I will consider your suggestion when we open this class next time. I personally agree that reading paper is helpful in the sense that 1) it is well presented and 2) it resolves all subtleties coming from imprecise understanding. However, there are some problems that should be considered (e.g. it requires deep theoretical background to get some intuition by reading the paper). 

For this semester, since we have only one lecture left and it will be a Q&A session (https://github.com/kaist-cp/cs431/issues/950), it seems it is difficult to reserve a class for reading the paper. Instead, if you are interested, I suggest you to come to the tomorrow's Q&A session and ask questions while reading the paper.
