### ISSUE TITLE
[Question] Timeout on growable_array stress_concurrent with cargo_asan

### ISSUE THREAD

**Issue by kjh618** [kaist-cp/cs431#956]
My growable_array implementation times out on only the stress_concurrent test with cargo_asan.
If I manually run `cargo_asan test --release --test growable_array stress_concurrent`, it succeeds in about 130s on my laptop.
Running the growable_array stress_concurrent test with cargo or cargo_tsan succeeds within the timeout, and all the other cargo/cargo_asan/cargo_tsan tests for growable_array succeeds as well.

If I put a print statement at the beginning of `GrowableArray`'s `drop`, it is printed almost at the end of the 130s, so it seems the problem is in my `get` implementation.
Are there some code patterns that make ASAN particularly slow? Or could my `get` implementation be buggy in such a way that makes all the other tests succeed?

**Comment by kingdoctor123** [comment]
Since there are tons of reasons for inefficient implementation, I may not give you correct advice. In my experience, I saw some students having the same problem, and they typically solved the problem by reducing the number of CAS attempts. Especially, when performing CAS from null to an address of a new segment, it is beneficial to 1) load from the memory and 2) perform the CAS only if loaded value is indeed null. I found that this method allowed 6 times increase in speed. I'm not sure this applies to you, but I hope you can find out your own solution.

**Comment by kjh618** [comment]
That was indeed the problem. Checking is_null before CAS solved the issue. Thanks!
